/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.vcms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Category service. Represents a row in the &quot;vcms_Category&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viettel.portal.vcms.model.impl.CategoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viettel.portal.vcms.model.impl.CategoryImpl}.
 * </p>
 *
 * @author chuchv
 * @see Category
 * @see com.viettel.portal.vcms.model.impl.CategoryImpl
 * @see com.viettel.portal.vcms.model.impl.CategoryModelImpl
 * @generated
 */
public interface CategoryModel extends BaseModel<Category>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a category model instance should use the {@link Category} interface instead.
	 */

	/**
	 * Returns the primary key of this category.
	 *
	 * @return the primary key of this category
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this category.
	 *
	 * @param primaryKey the primary key of this category
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the category ID of this category.
	 *
	 * @return the category ID of this category
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this category.
	 *
	 * @param categoryId the category ID of this category
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the group ID of this category.
	 *
	 * @return the group ID of this category
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this category.
	 *
	 * @param groupId the group ID of this category
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this category.
	 *
	 * @return the company ID of this category
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this category.
	 *
	 * @param companyId the company ID of this category
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this category.
	 *
	 * @return the user ID of this category
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this category.
	 *
	 * @param userId the user ID of this category
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this category.
	 *
	 * @return the user uuid of this category
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this category.
	 *
	 * @param userUuid the user uuid of this category
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this category.
	 *
	 * @return the user name of this category
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this category.
	 *
	 * @param userName the user name of this category
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this category.
	 *
	 * @return the create date of this category
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this category.
	 *
	 * @param createDate the create date of this category
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this category.
	 *
	 * @return the modified date of this category
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this category.
	 *
	 * @param modifiedDate the modified date of this category
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the category name of this category.
	 *
	 * @return the category name of this category
	 */
	@AutoEscape
	public String getCategoryName();

	/**
	 * Sets the category name of this category.
	 *
	 * @param categoryName the category name of this category
	 */
	public void setCategoryName(String categoryName);

	/**
	 * Returns the category desc of this category.
	 *
	 * @return the category desc of this category
	 */
	@AutoEscape
	public String getCategoryDesc();

	/**
	 * Sets the category desc of this category.
	 *
	 * @param categoryDesc the category desc of this category
	 */
	public void setCategoryDesc(String categoryDesc);

	/**
	 * Returns the sort order of this category.
	 *
	 * @return the sort order of this category
	 */
	public int getSortOrder();

	/**
	 * Sets the sort order of this category.
	 *
	 * @param sortOrder the sort order of this category
	 */
	public void setSortOrder(int sortOrder);

	/**
	 * Returns the archived of this category.
	 *
	 * @return the archived of this category
	 */
	public boolean getArchived();

	/**
	 * Returns <code>true</code> if this category is archived.
	 *
	 * @return <code>true</code> if this category is archived; <code>false</code> otherwise
	 */
	public boolean isArchived();

	/**
	 * Sets whether this category is archived.
	 *
	 * @param archived the archived of this category
	 */
	public void setArchived(boolean archived);

	/**
	 * Returns the layout ID of this category.
	 *
	 * @return the layout ID of this category
	 */
	public long getLayoutId();

	/**
	 * Sets the layout ID of this category.
	 *
	 * @param layoutId the layout ID of this category
	 */
	public void setLayoutId(long layoutId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.viettel.portal.vcms.model.Category category);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.viettel.portal.vcms.model.Category> toCacheModel();

	@Override
	public com.viettel.portal.vcms.model.Category toEscapedModel();

	@Override
	public com.viettel.portal.vcms.model.Category toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}