/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.vcms.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ContentTypeCost service. Represents a row in the &quot;vcms_Content_TypeCost&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viettel.portal.vcms.model.impl.ContentTypeCostModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viettel.portal.vcms.model.impl.ContentTypeCostImpl}.
 * </p>
 *
 * @author chuchv
 * @see ContentTypeCost
 * @see com.viettel.portal.vcms.model.impl.ContentTypeCostImpl
 * @see com.viettel.portal.vcms.model.impl.ContentTypeCostModelImpl
 * @generated
 */
public interface ContentTypeCostModel extends BaseModel<ContentTypeCost> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a content type cost model instance should use the {@link ContentTypeCost} interface instead.
	 */

	/**
	 * Returns the primary key of this content type cost.
	 *
	 * @return the primary key of this content type cost
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this content type cost.
	 *
	 * @param primaryKey the primary key of this content type cost
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cost ID of this content type cost.
	 *
	 * @return the cost ID of this content type cost
	 */
	public long getCostId();

	/**
	 * Sets the cost ID of this content type cost.
	 *
	 * @param costId the cost ID of this content type cost
	 */
	public void setCostId(long costId);

	/**
	 * Returns the group ID of this content type cost.
	 *
	 * @return the group ID of this content type cost
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this content type cost.
	 *
	 * @param groupId the group ID of this content type cost
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the content type i d of this content type cost.
	 *
	 * @return the content type i d of this content type cost
	 */
	public long getContentTypeID();

	/**
	 * Sets the content type i d of this content type cost.
	 *
	 * @param contentTypeID the content type i d of this content type cost
	 */
	public void setContentTypeID(long contentTypeID);

	/**
	 * Returns the from date of this content type cost.
	 *
	 * @return the from date of this content type cost
	 */
	public Date getFromDate();

	/**
	 * Sets the from date of this content type cost.
	 *
	 * @param fromDate the from date of this content type cost
	 */
	public void setFromDate(Date fromDate);

	/**
	 * Returns the to date of this content type cost.
	 *
	 * @return the to date of this content type cost
	 */
	public Date getToDate();

	/**
	 * Sets the to date of this content type cost.
	 *
	 * @param toDate the to date of this content type cost
	 */
	public void setToDate(Date toDate);

	/**
	 * Returns the cost of this content type cost.
	 *
	 * @return the cost of this content type cost
	 */
	public double getCost();

	/**
	 * Sets the cost of this content type cost.
	 *
	 * @param cost the cost of this content type cost
	 */
	public void setCost(double cost);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.viettel.portal.vcms.model.ContentTypeCost contentTypeCost);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.viettel.portal.vcms.model.ContentTypeCost> toCacheModel();

	@Override
	public com.viettel.portal.vcms.model.ContentTypeCost toEscapedModel();

	@Override
	public com.viettel.portal.vcms.model.ContentTypeCost toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}