/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.vcms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Content service. Represents a row in the &quot;vcms_Content&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viettel.portal.vcms.model.impl.ContentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viettel.portal.vcms.model.impl.ContentImpl}.
 * </p>
 *
 * @author chuchv
 * @see Content
 * @see com.viettel.portal.vcms.model.impl.ContentImpl
 * @see com.viettel.portal.vcms.model.impl.ContentModelImpl
 * @generated
 */
public interface ContentModel extends BaseModel<Content>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a content model instance should use the {@link Content} interface instead.
	 */

	/**
	 * Returns the primary key of this content.
	 *
	 * @return the primary key of this content
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this content.
	 *
	 * @param primaryKey the primary key of this content
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the auto ID of this content.
	 *
	 * @return the auto ID of this content
	 */
	public long getAutoId();

	/**
	 * Sets the auto ID of this content.
	 *
	 * @param autoId the auto ID of this content
	 */
	public void setAutoId(long autoId);

	/**
	 * Returns the content ID of this content.
	 *
	 * @return the content ID of this content
	 */
	public long getContentId();

	/**
	 * Sets the content ID of this content.
	 *
	 * @param contentId the content ID of this content
	 */
	public void setContentId(long contentId);

	/**
	 * Returns the group ID of this content.
	 *
	 * @return the group ID of this content
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this content.
	 *
	 * @param groupId the group ID of this content
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this content.
	 *
	 * @return the company ID of this content
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this content.
	 *
	 * @param companyId the company ID of this content
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this content.
	 *
	 * @return the user ID of this content
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this content.
	 *
	 * @param userId the user ID of this content
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this content.
	 *
	 * @return the user uuid of this content
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this content.
	 *
	 * @param userUuid the user uuid of this content
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this content.
	 *
	 * @return the user name of this content
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this content.
	 *
	 * @param userName the user name of this content
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this content.
	 *
	 * @return the create date of this content
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this content.
	 *
	 * @param createDate the create date of this content
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this content.
	 *
	 * @return the modified date of this content
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this content.
	 *
	 * @param modifiedDate the modified date of this content
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the pre version of this content.
	 *
	 * @return the pre version of this content
	 */
	public int getPreVersion();

	/**
	 * Sets the pre version of this content.
	 *
	 * @param preVersion the pre version of this content
	 */
	public void setPreVersion(int preVersion);

	/**
	 * Returns the version of this content.
	 *
	 * @return the version of this content
	 */
	public int getVersion();

	/**
	 * Sets the version of this content.
	 *
	 * @param version the version of this content
	 */
	public void setVersion(int version);

	/**
	 * Returns the subversion of this content.
	 *
	 * @return the subversion of this content
	 */
	public float getSubversion();

	/**
	 * Sets the subversion of this content.
	 *
	 * @param subversion the subversion of this content
	 */
	public void setSubversion(float subversion);

	/**
	 * Returns the sub title of this content.
	 *
	 * @return the sub title of this content
	 */
	@AutoEscape
	public String getSubTitle();

	/**
	 * Sets the sub title of this content.
	 *
	 * @param subTitle the sub title of this content
	 */
	public void setSubTitle(String subTitle);

	/**
	 * Returns the title of this content.
	 *
	 * @return the title of this content
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this content.
	 *
	 * @param title the title of this content
	 */
	public void setTitle(String title);

	/**
	 * Returns the summary of this content.
	 *
	 * @return the summary of this content
	 */
	@AutoEscape
	public String getSummary();

	/**
	 * Sets the summary of this content.
	 *
	 * @param summary the summary of this content
	 */
	public void setSummary(String summary);

	/**
	 * Returns the sub content of this content.
	 *
	 * @return the sub content of this content
	 */
	@AutoEscape
	public String getSubContent();

	/**
	 * Sets the sub content of this content.
	 *
	 * @param subContent the sub content of this content
	 */
	public void setSubContent(String subContent);

	/**
	 * Returns the content of this content.
	 *
	 * @return the content of this content
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this content.
	 *
	 * @param content the content of this content
	 */
	public void setContent(String content);

	/**
	 * Returns the small image ID of this content.
	 *
	 * @return the small image ID of this content
	 */
	public long getSmallImageId();

	/**
	 * Sets the small image ID of this content.
	 *
	 * @param smallImageId the small image ID of this content
	 */
	public void setSmallImageId(long smallImageId);

	/**
	 * Returns the small image url of this content.
	 *
	 * @return the small image url of this content
	 */
	@AutoEscape
	public String getSmallImageUrl();

	/**
	 * Sets the small image url of this content.
	 *
	 * @param smallImageUrl the small image url of this content
	 */
	public void setSmallImageUrl(String smallImageUrl);

	/**
	 * Returns the category ID of this content.
	 *
	 * @return the category ID of this content
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this content.
	 *
	 * @param categoryId the category ID of this content
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the copy right of this content.
	 *
	 * @return the copy right of this content
	 */
	@AutoEscape
	public String getCopyRight();

	/**
	 * Sets the copy right of this content.
	 *
	 * @param copyRight the copy right of this content
	 */
	public void setCopyRight(String copyRight);

	/**
	 * Returns the status of this content.
	 *
	 * @return the status of this content
	 */
	public int getStatus();

	/**
	 * Sets the status of this content.
	 *
	 * @param status the status of this content
	 */
	public void setStatus(int status);

	/**
	 * Returns the url title of this content.
	 *
	 * @return the url title of this content
	 */
	@AutoEscape
	public String getUrlTitle();

	/**
	 * Sets the url title of this content.
	 *
	 * @param urlTitle the url title of this content
	 */
	public void setUrlTitle(String urlTitle);

	/**
	 * Returns the news type of this content.
	 *
	 * @return the news type of this content
	 */
	public int getNewsType();

	/**
	 * Sets the news type of this content.
	 *
	 * @param newsType the news type of this content
	 */
	public void setNewsType(int newsType);

	/**
	 * Returns the image url of this content.
	 *
	 * @return the image url of this content
	 */
	@AutoEscape
	public String getImageUrl();

	/**
	 * Sets the image url of this content.
	 *
	 * @param imageUrl the image url of this content
	 */
	public void setImageUrl(String imageUrl);

	/**
	 * Returns the is legal content of this content.
	 *
	 * @return the is legal content of this content
	 */
	public boolean getIsLegalContent();

	/**
	 * Returns <code>true</code> if this content is is legal content.
	 *
	 * @return <code>true</code> if this content is is legal content; <code>false</code> otherwise
	 */
	public boolean isIsLegalContent();

	/**
	 * Sets whether this content is is legal content.
	 *
	 * @param isLegalContent the is legal content of this content
	 */
	public void setIsLegalContent(boolean isLegalContent);

	/**
	 * Returns the image caption of this content.
	 *
	 * @return the image caption of this content
	 */
	@AutoEscape
	public String getImageCaption();

	/**
	 * Sets the image caption of this content.
	 *
	 * @param imageCaption the image caption of this content
	 */
	public void setImageCaption(String imageCaption);

	/**
	 * Returns the image position of this content.
	 *
	 * @return the image position of this content
	 */
	public int getImagePosition();

	/**
	 * Sets the image position of this content.
	 *
	 * @param imagePosition the image position of this content
	 */
	public void setImagePosition(int imagePosition);

	/**
	 * Returns the created by user ID of this content.
	 *
	 * @return the created by user ID of this content
	 */
	public long getCreatedByUserId();

	/**
	 * Sets the created by user ID of this content.
	 *
	 * @param createdByUserId the created by user ID of this content
	 */
	public void setCreatedByUserId(long createdByUserId);

	/**
	 * Returns the created by user uuid of this content.
	 *
	 * @return the created by user uuid of this content
	 * @throws SystemException if a system exception occurred
	 */
	public String getCreatedByUserUuid() throws SystemException;

	/**
	 * Sets the created by user uuid of this content.
	 *
	 * @param createdByUserUuid the created by user uuid of this content
	 */
	public void setCreatedByUserUuid(String createdByUserUuid);

	/**
	 * Returns the edited by user ID of this content.
	 *
	 * @return the edited by user ID of this content
	 */
	public long getEditedByUserId();

	/**
	 * Sets the edited by user ID of this content.
	 *
	 * @param editedByUserId the edited by user ID of this content
	 */
	public void setEditedByUserId(long editedByUserId);

	/**
	 * Returns the edited by user uuid of this content.
	 *
	 * @return the edited by user uuid of this content
	 * @throws SystemException if a system exception occurred
	 */
	public String getEditedByUserUuid() throws SystemException;

	/**
	 * Sets the edited by user uuid of this content.
	 *
	 * @param editedByUserUuid the edited by user uuid of this content
	 */
	public void setEditedByUserUuid(String editedByUserUuid);

	/**
	 * Returns the reviewed by user ID of this content.
	 *
	 * @return the reviewed by user ID of this content
	 */
	public long getReviewedByUserId();

	/**
	 * Sets the reviewed by user ID of this content.
	 *
	 * @param reviewedByUserId the reviewed by user ID of this content
	 */
	public void setReviewedByUserId(long reviewedByUserId);

	/**
	 * Returns the reviewed by user uuid of this content.
	 *
	 * @return the reviewed by user uuid of this content
	 * @throws SystemException if a system exception occurred
	 */
	public String getReviewedByUserUuid() throws SystemException;

	/**
	 * Sets the reviewed by user uuid of this content.
	 *
	 * @param reviewedByUserUuid the reviewed by user uuid of this content
	 */
	public void setReviewedByUserUuid(String reviewedByUserUuid);

	/**
	 * Returns the published by user ID of this content.
	 *
	 * @return the published by user ID of this content
	 */
	public long getPublishedByUserId();

	/**
	 * Sets the published by user ID of this content.
	 *
	 * @param publishedByUserId the published by user ID of this content
	 */
	public void setPublishedByUserId(long publishedByUserId);

	/**
	 * Returns the published by user uuid of this content.
	 *
	 * @return the published by user uuid of this content
	 * @throws SystemException if a system exception occurred
	 */
	public String getPublishedByUserUuid() throws SystemException;

	/**
	 * Sets the published by user uuid of this content.
	 *
	 * @param publishedByUserUuid the published by user uuid of this content
	 */
	public void setPublishedByUserUuid(String publishedByUserUuid);

	/**
	 * Returns the created by user name of this content.
	 *
	 * @return the created by user name of this content
	 */
	@AutoEscape
	public String getCreatedByUserName();

	/**
	 * Sets the created by user name of this content.
	 *
	 * @param createdByUserName the created by user name of this content
	 */
	public void setCreatedByUserName(String createdByUserName);

	/**
	 * Returns the edited by user name of this content.
	 *
	 * @return the edited by user name of this content
	 */
	@AutoEscape
	public String getEditedByUserName();

	/**
	 * Sets the edited by user name of this content.
	 *
	 * @param editedByUserName the edited by user name of this content
	 */
	public void setEditedByUserName(String editedByUserName);

	/**
	 * Returns the reviewed by user name of this content.
	 *
	 * @return the reviewed by user name of this content
	 */
	@AutoEscape
	public String getReviewedByUserName();

	/**
	 * Sets the reviewed by user name of this content.
	 *
	 * @param reviewedByUserName the reviewed by user name of this content
	 */
	public void setReviewedByUserName(String reviewedByUserName);

	/**
	 * Returns the published by user name of this content.
	 *
	 * @return the published by user name of this content
	 */
	@AutoEscape
	public String getPublishedByUserName();

	/**
	 * Sets the published by user name of this content.
	 *
	 * @param publishedByUserName the published by user name of this content
	 */
	public void setPublishedByUserName(String publishedByUserName);

	/**
	 * Returns the author of this content.
	 *
	 * @return the author of this content
	 */
	@AutoEscape
	public String getAuthor();

	/**
	 * Sets the author of this content.
	 *
	 * @param author the author of this content
	 */
	public void setAuthor(String author);

	/**
	 * Returns the job title of this content.
	 *
	 * @return the job title of this content
	 */
	@AutoEscape
	public String getJobTitle();

	/**
	 * Sets the job title of this content.
	 *
	 * @param jobTitle the job title of this content
	 */
	public void setJobTitle(String jobTitle);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.viettel.portal.vcms.model.Content content);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.viettel.portal.vcms.model.Content> toCacheModel();

	@Override
	public com.viettel.portal.vcms.model.Content toEscapedModel();

	@Override
	public com.viettel.portal.vcms.model.Content toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}