/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.vcms.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Legal_Distribution service. Represents a row in the &quot;Distribution&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viettel.portal.vcms.model.impl.Legal_DistributionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viettel.portal.vcms.model.impl.Legal_DistributionImpl}.
 * </p>
 *
 * @author chuchv
 * @see Legal_Distribution
 * @see com.viettel.portal.vcms.model.impl.Legal_DistributionImpl
 * @see com.viettel.portal.vcms.model.impl.Legal_DistributionModelImpl
 * @generated
 */
public interface Legal_DistributionModel extends BaseModel<Legal_Distribution> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a legal_ distribution model instance should use the {@link Legal_Distribution} interface instead.
	 */

	/**
	 * Returns the primary key of this legal_ distribution.
	 *
	 * @return the primary key of this legal_ distribution
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this legal_ distribution.
	 *
	 * @param primaryKey the primary key of this legal_ distribution
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the i d of this legal_ distribution.
	 *
	 * @return the i d of this legal_ distribution
	 */
	public int getID();

	/**
	 * Sets the i d of this legal_ distribution.
	 *
	 * @param ID the i d of this legal_ distribution
	 */
	public void setID(int ID);

	/**
	 * Returns the content i d of this legal_ distribution.
	 *
	 * @return the content i d of this legal_ distribution
	 */
	public int getContentID();

	/**
	 * Sets the content i d of this legal_ distribution.
	 *
	 * @param ContentID the content i d of this legal_ distribution
	 */
	public void setContentID(int ContentID);

	/**
	 * Returns the version of this legal_ distribution.
	 *
	 * @return the version of this legal_ distribution
	 */
	public int getVersion();

	/**
	 * Sets the version of this legal_ distribution.
	 *
	 * @param Version the version of this legal_ distribution
	 */
	public void setVersion(int Version);

	/**
	 * Returns the zone i d of this legal_ distribution.
	 *
	 * @return the zone i d of this legal_ distribution
	 */
	public int getZoneID();

	/**
	 * Sets the zone i d of this legal_ distribution.
	 *
	 * @param ZoneID the zone i d of this legal_ distribution
	 */
	public void setZoneID(int ZoneID);

	/**
	 * Returns the distributed date of this legal_ distribution.
	 *
	 * @return the distributed date of this legal_ distribution
	 */
	public Date getDistributedDate();

	/**
	 * Sets the distributed date of this legal_ distribution.
	 *
	 * @param DistributedDate the distributed date of this legal_ distribution
	 */
	public void setDistributedDate(Date DistributedDate);

	/**
	 * Returns the ranking of this legal_ distribution.
	 *
	 * @return the ranking of this legal_ distribution
	 */
	public int getRanking();

	/**
	 * Sets the ranking of this legal_ distribution.
	 *
	 * @param Ranking the ranking of this legal_ distribution
	 */
	public void setRanking(int Ranking);

	/**
	 * Returns the allow discussion of this legal_ distribution.
	 *
	 * @return the allow discussion of this legal_ distribution
	 */
	public boolean getAllowDiscussion();

	/**
	 * Returns <code>true</code> if this legal_ distribution is allow discussion.
	 *
	 * @return <code>true</code> if this legal_ distribution is allow discussion; <code>false</code> otherwise
	 */
	public boolean isAllowDiscussion();

	/**
	 * Sets whether this legal_ distribution is allow discussion.
	 *
	 * @param AllowDiscussion the allow discussion of this legal_ distribution
	 */
	public void setAllowDiscussion(boolean AllowDiscussion);

	/**
	 * Returns the viewed count of this legal_ distribution.
	 *
	 * @return the viewed count of this legal_ distribution
	 */
	public int getViewedCount();

	/**
	 * Sets the viewed count of this legal_ distribution.
	 *
	 * @param ViewedCount the viewed count of this legal_ distribution
	 */
	public void setViewedCount(int ViewedCount);

	/**
	 * Returns the mailed count of this legal_ distribution.
	 *
	 * @return the mailed count of this legal_ distribution
	 */
	public int getMailedCount();

	/**
	 * Sets the mailed count of this legal_ distribution.
	 *
	 * @param MailedCount the mailed count of this legal_ distribution
	 */
	public void setMailedCount(int MailedCount);

	/**
	 * Returns the rated count of this legal_ distribution.
	 *
	 * @return the rated count of this legal_ distribution
	 */
	public int getRatedCount();

	/**
	 * Sets the rated count of this legal_ distribution.
	 *
	 * @param RatedCount the rated count of this legal_ distribution
	 */
	public void setRatedCount(int RatedCount);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.viettel.portal.vcms.model.Legal_Distribution legal_Distribution);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.viettel.portal.vcms.model.Legal_Distribution> toCacheModel();

	@Override
	public com.viettel.portal.vcms.model.Legal_Distribution toEscapedModel();

	@Override
	public com.viettel.portal.vcms.model.Legal_Distribution toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}