/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.vcms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Legal_Zone service. Represents a row in the &quot;Zone&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viettel.portal.vcms.model.impl.Legal_ZoneModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viettel.portal.vcms.model.impl.Legal_ZoneImpl}.
 * </p>
 *
 * @author chuchv
 * @see Legal_Zone
 * @see com.viettel.portal.vcms.model.impl.Legal_ZoneImpl
 * @see com.viettel.portal.vcms.model.impl.Legal_ZoneModelImpl
 * @generated
 */
public interface Legal_ZoneModel extends BaseModel<Legal_Zone> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a legal_ zone model instance should use the {@link Legal_Zone} interface instead.
	 */

	/**
	 * Returns the primary key of this legal_ zone.
	 *
	 * @return the primary key of this legal_ zone
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this legal_ zone.
	 *
	 * @param primaryKey the primary key of this legal_ zone
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the i d of this legal_ zone.
	 *
	 * @return the i d of this legal_ zone
	 */
	public int getID();

	/**
	 * Sets the i d of this legal_ zone.
	 *
	 * @param ID the i d of this legal_ zone
	 */
	public void setID(int ID);

	/**
	 * Returns the creation date of this legal_ zone.
	 *
	 * @return the creation date of this legal_ zone
	 */
	public Date getCreationDate();

	/**
	 * Sets the creation date of this legal_ zone.
	 *
	 * @param CreationDate the creation date of this legal_ zone
	 */
	public void setCreationDate(Date CreationDate);

	/**
	 * Returns the modified date of this legal_ zone.
	 *
	 * @return the modified date of this legal_ zone
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this legal_ zone.
	 *
	 * @param ModifiedDate the modified date of this legal_ zone
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the name of this legal_ zone.
	 *
	 * @return the name of this legal_ zone
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this legal_ zone.
	 *
	 * @param Name the name of this legal_ zone
	 */
	public void setName(String Name);

	/**
	 * Returns the url of this legal_ zone.
	 *
	 * @return the url of this legal_ zone
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this legal_ zone.
	 *
	 * @param Url the url of this legal_ zone
	 */
	public void setUrl(String Url);

	/**
	 * Returns the description of this legal_ zone.
	 *
	 * @return the description of this legal_ zone
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this legal_ zone.
	 *
	 * @param Description the description of this legal_ zone
	 */
	public void setDescription(String Description);

	/**
	 * Returns the parent i d of this legal_ zone.
	 *
	 * @return the parent i d of this legal_ zone
	 */
	public int getParentID();

	/**
	 * Sets the parent i d of this legal_ zone.
	 *
	 * @param ParentID the parent i d of this legal_ zone
	 */
	public void setParentID(int ParentID);

	/**
	 * Returns the real url of this legal_ zone.
	 *
	 * @return the real url of this legal_ zone
	 */
	@AutoEscape
	public String getRealUrl();

	/**
	 * Sets the real url of this legal_ zone.
	 *
	 * @param RealUrl the real url of this legal_ zone
	 */
	public void setRealUrl(String RealUrl);

	/**
	 * Returns the visible of this legal_ zone.
	 *
	 * @return the visible of this legal_ zone
	 */
	public boolean getVisible();

	/**
	 * Returns <code>true</code> if this legal_ zone is visible.
	 *
	 * @return <code>true</code> if this legal_ zone is visible; <code>false</code> otherwise
	 */
	public boolean isVisible();

	/**
	 * Sets whether this legal_ zone is visible.
	 *
	 * @param Visible the visible of this legal_ zone
	 */
	public void setVisible(boolean Visible);

	/**
	 * Returns the archived of this legal_ zone.
	 *
	 * @return the archived of this legal_ zone
	 */
	public boolean getArchived();

	/**
	 * Returns <code>true</code> if this legal_ zone is archived.
	 *
	 * @return <code>true</code> if this legal_ zone is archived; <code>false</code> otherwise
	 */
	public boolean isArchived();

	/**
	 * Sets whether this legal_ zone is archived.
	 *
	 * @param Archived the archived of this legal_ zone
	 */
	public void setArchived(boolean Archived);

	/**
	 * Returns the sort order of this legal_ zone.
	 *
	 * @return the sort order of this legal_ zone
	 */
	public int getSortOrder();

	/**
	 * Sets the sort order of this legal_ zone.
	 *
	 * @param SortOrder the sort order of this legal_ zone
	 */
	public void setSortOrder(int SortOrder);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.viettel.portal.vcms.model.Legal_Zone legal_Zone);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.viettel.portal.vcms.model.Legal_Zone> toCacheModel();

	@Override
	public com.viettel.portal.vcms.model.Legal_Zone toEscapedModel();

	@Override
	public com.viettel.portal.vcms.model.Legal_Zone toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}