/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.vcms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Legal_Comment service. Represents a row in the &quot;Comment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viettel.portal.vcms.model.impl.Legal_CommentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viettel.portal.vcms.model.impl.Legal_CommentImpl}.
 * </p>
 *
 * @author chuchv
 * @see Legal_Comment
 * @see com.viettel.portal.vcms.model.impl.Legal_CommentImpl
 * @see com.viettel.portal.vcms.model.impl.Legal_CommentModelImpl
 * @generated
 */
public interface Legal_CommentModel extends BaseModel<Legal_Comment> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a legal_ comment model instance should use the {@link Legal_Comment} interface instead.
	 */

	/**
	 * Returns the primary key of this legal_ comment.
	 *
	 * @return the primary key of this legal_ comment
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this legal_ comment.
	 *
	 * @param primaryKey the primary key of this legal_ comment
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the i d of this legal_ comment.
	 *
	 * @return the i d of this legal_ comment
	 */
	public int getID();

	/**
	 * Sets the i d of this legal_ comment.
	 *
	 * @param ID the i d of this legal_ comment
	 */
	public void setID(int ID);

	/**
	 * Returns the distribution i d of this legal_ comment.
	 *
	 * @return the distribution i d of this legal_ comment
	 */
	public int getDistributionID();

	/**
	 * Sets the distribution i d of this legal_ comment.
	 *
	 * @param DistributionID the distribution i d of this legal_ comment
	 */
	public void setDistributionID(int DistributionID);

	/**
	 * Returns the fullname of this legal_ comment.
	 *
	 * @return the fullname of this legal_ comment
	 */
	@AutoEscape
	public String getFullname();

	/**
	 * Sets the fullname of this legal_ comment.
	 *
	 * @param Fullname the fullname of this legal_ comment
	 */
	public void setFullname(String Fullname);

	/**
	 * Returns the address of this legal_ comment.
	 *
	 * @return the address of this legal_ comment
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this legal_ comment.
	 *
	 * @param Address the address of this legal_ comment
	 */
	public void setAddress(String Address);

	/**
	 * Returns the email of this legal_ comment.
	 *
	 * @return the email of this legal_ comment
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this legal_ comment.
	 *
	 * @param Email the email of this legal_ comment
	 */
	public void setEmail(String Email);

	/**
	 * Returns the body of this legal_ comment.
	 *
	 * @return the body of this legal_ comment
	 */
	@AutoEscape
	public String getBody();

	/**
	 * Sets the body of this legal_ comment.
	 *
	 * @param Body the body of this legal_ comment
	 */
	public void setBody(String Body);

	/**
	 * Returns the visible of this legal_ comment.
	 *
	 * @return the visible of this legal_ comment
	 */
	public boolean getVisible();

	/**
	 * Returns <code>true</code> if this legal_ comment is visible.
	 *
	 * @return <code>true</code> if this legal_ comment is visible; <code>false</code> otherwise
	 */
	public boolean isVisible();

	/**
	 * Sets whether this legal_ comment is visible.
	 *
	 * @param Visible the visible of this legal_ comment
	 */
	public void setVisible(boolean Visible);

	/**
	 * Returns the creation date of this legal_ comment.
	 *
	 * @return the creation date of this legal_ comment
	 */
	public Date getCreationDate();

	/**
	 * Sets the creation date of this legal_ comment.
	 *
	 * @param CreationDate the creation date of this legal_ comment
	 */
	public void setCreationDate(Date CreationDate);

	/**
	 * Returns the modified date of this legal_ comment.
	 *
	 * @return the modified date of this legal_ comment
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this legal_ comment.
	 *
	 * @param ModifiedDate the modified date of this legal_ comment
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the i p address of this legal_ comment.
	 *
	 * @return the i p address of this legal_ comment
	 */
	@AutoEscape
	public String getIPAddress();

	/**
	 * Sets the i p address of this legal_ comment.
	 *
	 * @param IPAddress the i p address of this legal_ comment
	 */
	public void setIPAddress(String IPAddress);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.viettel.portal.vcms.model.Legal_Comment legal_Comment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.viettel.portal.vcms.model.Legal_Comment> toCacheModel();

	@Override
	public com.viettel.portal.vcms.model.Legal_Comment toEscapedModel();

	@Override
	public com.viettel.portal.vcms.model.Legal_Comment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}