/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.videolibrary.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VLCategory service. Represents a row in the &quot;portal_videocategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viettel.portal.videolibrary.model.impl.VLCategoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viettel.portal.videolibrary.model.impl.VLCategoryImpl}.
 * </p>
 *
 * @author ChucHV
 * @see VLCategory
 * @see com.viettel.portal.videolibrary.model.impl.VLCategoryImpl
 * @see com.viettel.portal.videolibrary.model.impl.VLCategoryModelImpl
 * @generated
 */
public interface VLCategoryModel extends BaseModel<VLCategory>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a v l category model instance should use the {@link VLCategory} interface instead.
	 */

	/**
	 * Returns the primary key of this v l category.
	 *
	 * @return the primary key of this v l category
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this v l category.
	 *
	 * @param primaryKey the primary key of this v l category
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the category ID of this v l category.
	 *
	 * @return the category ID of this v l category
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this v l category.
	 *
	 * @param categoryId the category ID of this v l category
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the group ID of this v l category.
	 *
	 * @return the group ID of this v l category
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this v l category.
	 *
	 * @param groupId the group ID of this v l category
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this v l category.
	 *
	 * @return the company ID of this v l category
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this v l category.
	 *
	 * @param companyId the company ID of this v l category
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this v l category.
	 *
	 * @return the user ID of this v l category
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this v l category.
	 *
	 * @param userId the user ID of this v l category
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this v l category.
	 *
	 * @return the user uuid of this v l category
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this v l category.
	 *
	 * @param userUuid the user uuid of this v l category
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this v l category.
	 *
	 * @return the user name of this v l category
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this v l category.
	 *
	 * @param userName the user name of this v l category
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this v l category.
	 *
	 * @return the create date of this v l category
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this v l category.
	 *
	 * @param createDate the create date of this v l category
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this v l category.
	 *
	 * @return the modified date of this v l category
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this v l category.
	 *
	 * @param modifiedDate the modified date of this v l category
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the category name of this v l category.
	 *
	 * @return the category name of this v l category
	 */
	@AutoEscape
	public String getCategoryName();

	/**
	 * Sets the category name of this v l category.
	 *
	 * @param categoryName the category name of this v l category
	 */
	public void setCategoryName(String categoryName);

	/**
	 * Returns the invisible of this v l category.
	 *
	 * @return the invisible of this v l category
	 */
	public boolean getInvisible();

	/**
	 * Returns <code>true</code> if this v l category is invisible.
	 *
	 * @return <code>true</code> if this v l category is invisible; <code>false</code> otherwise
	 */
	public boolean isInvisible();

	/**
	 * Sets whether this v l category is invisible.
	 *
	 * @param invisible the invisible of this v l category
	 */
	public void setInvisible(boolean invisible);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.viettel.portal.videolibrary.model.VLCategory vlCategory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.viettel.portal.videolibrary.model.VLCategory> toCacheModel();

	@Override
	public com.viettel.portal.videolibrary.model.VLCategory toEscapedModel();

	@Override
	public com.viettel.portal.videolibrary.model.VLCategory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}