/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.videolibrary.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the VLVideoCategory service. Represents a row in the &quot;portal_videocategorymap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viettel.portal.videolibrary.model.impl.VLVideoCategoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viettel.portal.videolibrary.model.impl.VLVideoCategoryImpl}.
 * </p>
 *
 * @author ChucHV
 * @see VLVideoCategory
 * @see com.viettel.portal.videolibrary.model.impl.VLVideoCategoryImpl
 * @see com.viettel.portal.videolibrary.model.impl.VLVideoCategoryModelImpl
 * @generated
 */
public interface VLVideoCategoryModel extends BaseModel<VLVideoCategory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a v l video category model instance should use the {@link VLVideoCategory} interface instead.
	 */

	/**
	 * Returns the primary key of this v l video category.
	 *
	 * @return the primary key of this v l video category
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this v l video category.
	 *
	 * @param primaryKey the primary key of this v l video category
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this v l video category.
	 *
	 * @return the ID of this v l video category
	 */
	public long getId();

	/**
	 * Sets the ID of this v l video category.
	 *
	 * @param id the ID of this v l video category
	 */
	public void setId(long id);

	/**
	 * Returns the category ID of this v l video category.
	 *
	 * @return the category ID of this v l video category
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this v l video category.
	 *
	 * @param categoryId the category ID of this v l video category
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the video ID of this v l video category.
	 *
	 * @return the video ID of this v l video category
	 */
	public long getVideoId();

	/**
	 * Sets the video ID of this v l video category.
	 *
	 * @param videoId the video ID of this v l video category
	 */
	public void setVideoId(long videoId);

	/**
	 * Returns the group ID of this v l video category.
	 *
	 * @return the group ID of this v l video category
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this v l video category.
	 *
	 * @param groupId the group ID of this v l video category
	 */
	public void setGroupId(long groupId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.viettel.portal.videolibrary.model.VLVideoCategory vlVideoCategory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.viettel.portal.videolibrary.model.VLVideoCategory> toCacheModel();

	@Override
	public com.viettel.portal.videolibrary.model.VLVideoCategory toEscapedModel();

	@Override
	public com.viettel.portal.videolibrary.model.VLVideoCategory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}