/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.vbpq.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the NhomVanBan service. Represents a row in the &quot;portal_vbpq_nhom_van_ban&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viettel.portal.vbpq.model.impl.NhomVanBanModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viettel.portal.vbpq.model.impl.NhomVanBanImpl}.
 * </p>
 *
 * @author ChucHV
 * @see NhomVanBan
 * @see com.viettel.portal.vbpq.model.impl.NhomVanBanImpl
 * @see com.viettel.portal.vbpq.model.impl.NhomVanBanModelImpl
 * @generated
 */
public interface NhomVanBanModel extends BaseModel<NhomVanBan> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a nhom van ban model instance should use the {@link NhomVanBan} interface instead.
	 */

	/**
	 * Returns the primary key of this nhom van ban.
	 *
	 * @return the primary key of this nhom van ban
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this nhom van ban.
	 *
	 * @param primaryKey the primary key of this nhom van ban
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this nhom van ban.
	 *
	 * @return the ID of this nhom van ban
	 */
	public long getId();

	/**
	 * Sets the ID of this nhom van ban.
	 *
	 * @param id the ID of this nhom van ban
	 */
	public void setId(long id);

	/**
	 * Returns the ten nhom of this nhom van ban.
	 *
	 * @return the ten nhom of this nhom van ban
	 */
	@AutoEscape
	public String getTenNhom();

	/**
	 * Sets the ten nhom of this nhom van ban.
	 *
	 * @param tenNhom the ten nhom of this nhom van ban
	 */
	public void setTenNhom(String tenNhom);

	/**
	 * Returns the nguoi tao of this nhom van ban.
	 *
	 * @return the nguoi tao of this nhom van ban
	 */
	@AutoEscape
	public String getNguoiTao();

	/**
	 * Sets the nguoi tao of this nhom van ban.
	 *
	 * @param nguoiTao the nguoi tao of this nhom van ban
	 */
	public void setNguoiTao(String nguoiTao);

	/**
	 * Returns the nguoi tao ID of this nhom van ban.
	 *
	 * @return the nguoi tao ID of this nhom van ban
	 */
	public long getNguoiTaoId();

	/**
	 * Sets the nguoi tao ID of this nhom van ban.
	 *
	 * @param nguoiTaoId the nguoi tao ID of this nhom van ban
	 */
	public void setNguoiTaoId(long nguoiTaoId);

	/**
	 * Returns the ngay tao of this nhom van ban.
	 *
	 * @return the ngay tao of this nhom van ban
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this nhom van ban.
	 *
	 * @param ngayTao the ngay tao of this nhom van ban
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the ngay sua of this nhom van ban.
	 *
	 * @return the ngay sua of this nhom van ban
	 */
	public Date getNgaySua();

	/**
	 * Sets the ngay sua of this nhom van ban.
	 *
	 * @param ngaySua the ngay sua of this nhom van ban
	 */
	public void setNgaySua(Date ngaySua);

	/**
	 * Returns the nguoi sua of this nhom van ban.
	 *
	 * @return the nguoi sua of this nhom van ban
	 */
	@AutoEscape
	public String getNguoiSua();

	/**
	 * Sets the nguoi sua of this nhom van ban.
	 *
	 * @param nguoiSua the nguoi sua of this nhom van ban
	 */
	public void setNguoiSua(String nguoiSua);

	/**
	 * Returns the nguoi sua ID of this nhom van ban.
	 *
	 * @return the nguoi sua ID of this nhom van ban
	 */
	public long getNguoiSuaId();

	/**
	 * Sets the nguoi sua ID of this nhom van ban.
	 *
	 * @param nguoiSuaId the nguoi sua ID of this nhom van ban
	 */
	public void setNguoiSuaId(long nguoiSuaId);

	/**
	 * Returns the trang thai of this nhom van ban.
	 *
	 * @return the trang thai of this nhom van ban
	 */
	public int getTrangThai();

	/**
	 * Sets the trang thai of this nhom van ban.
	 *
	 * @param trangThai the trang thai of this nhom van ban
	 */
	public void setTrangThai(int trangThai);

	/**
	 * Returns the group ID of this nhom van ban.
	 *
	 * @return the group ID of this nhom van ban
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this nhom van ban.
	 *
	 * @param groupId the group ID of this nhom van ban
	 */
	public void setGroupId(long groupId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.viettel.portal.vbpq.model.NhomVanBan nhomVanBan);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.viettel.portal.vbpq.model.NhomVanBan> toCacheModel();

	@Override
	public com.viettel.portal.vbpq.model.NhomVanBan toEscapedModel();

	@Override
	public com.viettel.portal.vbpq.model.NhomVanBan toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}