/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.magazine.archive.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Content service. Represents a row in the &quot;ArchiveContent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viettel.portal.magazine.archive.model.impl.ContentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viettel.portal.magazine.archive.model.impl.ContentImpl}.
 * </p>
 *
 * @author namtv
 * @see Content
 * @see com.viettel.portal.magazine.archive.model.impl.ContentImpl
 * @see com.viettel.portal.magazine.archive.model.impl.ContentModelImpl
 * @generated
 */
public interface ContentModel extends BaseModel<Content> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a content model instance should use the {@link Content} interface instead.
	 */

	/**
	 * Returns the primary key of this content.
	 *
	 * @return the primary key of this content
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this content.
	 *
	 * @param primaryKey the primary key of this content
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the i d of this content.
	 *
	 * @return the i d of this content
	 */
	public int getID();

	/**
	 * Sets the i d of this content.
	 *
	 * @param ID the i d of this content
	 */
	public void setID(int ID);

	/**
	 * Returns the subject of this content.
	 *
	 * @return the subject of this content
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this content.
	 *
	 * @param Subject the subject of this content
	 */
	public void setSubject(String Subject);

	/**
	 * Returns the normal zone i d of this content.
	 *
	 * @return the normal zone i d of this content
	 */
	public int getNormalZoneID();

	/**
	 * Sets the normal zone i d of this content.
	 *
	 * @param NormalZoneID the normal zone i d of this content
	 */
	public void setNormalZoneID(int NormalZoneID);

	/**
	 * Returns the special zone i d of this content.
	 *
	 * @return the special zone i d of this content
	 */
	public int getSpecialZoneID();

	/**
	 * Sets the special zone i d of this content.
	 *
	 * @param SpecialZoneID the special zone i d of this content
	 */
	public void setSpecialZoneID(int SpecialZoneID);

	/**
	 * Returns the file url of this content.
	 *
	 * @return the file url of this content
	 */
	@AutoEscape
	public String getFileUrl();

	/**
	 * Sets the file url of this content.
	 *
	 * @param FileUrl the file url of this content
	 */
	public void setFileUrl(String FileUrl);

	/**
	 * Returns the author of this content.
	 *
	 * @return the author of this content
	 */
	@AutoEscape
	public String getAuthor();

	/**
	 * Sets the author of this content.
	 *
	 * @param Author the author of this content
	 */
	public void setAuthor(String Author);

	/**
	 * Returns the author title of this content.
	 *
	 * @return the author title of this content
	 */
	@AutoEscape
	public String getAuthorTitle();

	/**
	 * Sets the author title of this content.
	 *
	 * @param AuthorTitle the author title of this content
	 */
	public void setAuthorTitle(String AuthorTitle);

	/**
	 * Returns the magazine i d of this content.
	 *
	 * @return the magazine i d of this content
	 */
	public int getMagazineID();

	/**
	 * Sets the magazine i d of this content.
	 *
	 * @param MagazineID the magazine i d of this content
	 */
	public void setMagazineID(int MagazineID);

	/**
	 * Returns the sort order of this content.
	 *
	 * @return the sort order of this content
	 */
	public int getSortOrder();

	/**
	 * Sets the sort order of this content.
	 *
	 * @param SortOrder the sort order of this content
	 */
	public void setSortOrder(int SortOrder);

	/**
	 * Returns the creation date of this content.
	 *
	 * @return the creation date of this content
	 */
	public Date getCreationDate();

	/**
	 * Sets the creation date of this content.
	 *
	 * @param CreationDate the creation date of this content
	 */
	public void setCreationDate(Date CreationDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.viettel.portal.magazine.archive.model.Content content);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.viettel.portal.magazine.archive.model.Content> toCacheModel();

	@Override
	public com.viettel.portal.magazine.archive.model.Content toEscapedModel();

	@Override
	public com.viettel.portal.magazine.archive.model.Content toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}