/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.magazine.archive.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Magazine service. Represents a row in the &quot;ArchiveMagazine&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viettel.portal.magazine.archive.model.impl.MagazineModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viettel.portal.magazine.archive.model.impl.MagazineImpl}.
 * </p>
 *
 * @author namtv
 * @see Magazine
 * @see com.viettel.portal.magazine.archive.model.impl.MagazineImpl
 * @see com.viettel.portal.magazine.archive.model.impl.MagazineModelImpl
 * @generated
 */
public interface MagazineModel extends BaseModel<Magazine> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a magazine model instance should use the {@link Magazine} interface instead.
	 */

	/**
	 * Returns the primary key of this magazine.
	 *
	 * @return the primary key of this magazine
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this magazine.
	 *
	 * @param primaryKey the primary key of this magazine
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the i d of this magazine.
	 *
	 * @return the i d of this magazine
	 */
	public int getID();

	/**
	 * Sets the i d of this magazine.
	 *
	 * @param ID the i d of this magazine
	 */
	public void setID(int ID);

	/**
	 * Returns the name of this magazine.
	 *
	 * @return the name of this magazine
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this magazine.
	 *
	 * @param Name the name of this magazine
	 */
	public void setName(String Name);

	/**
	 * Returns the publish number of this magazine.
	 *
	 * @return the publish number of this magazine
	 */
	public int getPublishNumber();

	/**
	 * Sets the publish number of this magazine.
	 *
	 * @param PublishNumber the publish number of this magazine
	 */
	public void setPublishNumber(int PublishNumber);

	/**
	 * Returns the publish month of this magazine.
	 *
	 * @return the publish month of this magazine
	 */
	public int getPublishMonth();

	/**
	 * Sets the publish month of this magazine.
	 *
	 * @param PublishMonth the publish month of this magazine
	 */
	public void setPublishMonth(int PublishMonth);

	/**
	 * Returns the publish year of this magazine.
	 *
	 * @return the publish year of this magazine
	 */
	public int getPublishYear();

	/**
	 * Sets the publish year of this magazine.
	 *
	 * @param PublishYear the publish year of this magazine
	 */
	public void setPublishYear(int PublishYear);

	/**
	 * Returns the image url of this magazine.
	 *
	 * @return the image url of this magazine
	 */
	@AutoEscape
	public String getImageUrl();

	/**
	 * Sets the image url of this magazine.
	 *
	 * @param ImageUrl the image url of this magazine
	 */
	public void setImageUrl(String ImageUrl);

	/**
	 * Returns the magazine type of this magazine.
	 *
	 * @return the magazine type of this magazine
	 */
	public int getMagazineType();

	/**
	 * Sets the magazine type of this magazine.
	 *
	 * @param MagazineType the magazine type of this magazine
	 */
	public void setMagazineType(int MagazineType);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.viettel.portal.magazine.archive.model.Magazine magazine);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.viettel.portal.magazine.archive.model.Magazine> toCacheModel();

	@Override
	public com.viettel.portal.magazine.archive.model.Magazine toEscapedModel();

	@Override
	public com.viettel.portal.magazine.archive.model.Magazine toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}