/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.liferay.viettel.portal.visitcounter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VisitCounterLog service. Represents a row in the &quot;VisitCounterLog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.viettel.portal.visitcounter.model.impl.VisitCounterLogModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.viettel.portal.visitcounter.model.impl.VisitCounterLogImpl}.
 * </p>
 *
 * @author hiepth6
 * @see VisitCounterLog
 * @see com.liferay.viettel.portal.visitcounter.model.impl.VisitCounterLogImpl
 * @see com.liferay.viettel.portal.visitcounter.model.impl.VisitCounterLogModelImpl
 * @generated
 */
public interface VisitCounterLogModel extends BaseModel<VisitCounterLog>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a visit counter log model instance should use the {@link VisitCounterLog} interface instead.
	 */

	/**
	 * Returns the primary key of this visit counter log.
	 *
	 * @return the primary key of this visit counter log
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this visit counter log.
	 *
	 * @param primaryKey the primary key of this visit counter log
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the visitor ip of this visit counter log.
	 *
	 * @return the visitor ip of this visit counter log
	 */
	@AutoEscape
	public String getVisitorIp();

	/**
	 * Sets the visitor ip of this visit counter log.
	 *
	 * @param visitorIp the visitor ip of this visit counter log
	 */
	public void setVisitorIp(String visitorIp);

	/**
	 * Returns the company ID of this visit counter log.
	 *
	 * @return the company ID of this visit counter log
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this visit counter log.
	 *
	 * @param companyId the company ID of this visit counter log
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this visit counter log.
	 *
	 * @return the group ID of this visit counter log
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this visit counter log.
	 *
	 * @param groupId the group ID of this visit counter log
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this visit counter log.
	 *
	 * @return the user ID of this visit counter log
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this visit counter log.
	 *
	 * @param userId the user ID of this visit counter log
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this visit counter log.
	 *
	 * @return the user uuid of this visit counter log
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this visit counter log.
	 *
	 * @param userUuid the user uuid of this visit counter log
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this visit counter log.
	 *
	 * @return the user name of this visit counter log
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this visit counter log.
	 *
	 * @param userName the user name of this visit counter log
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this visit counter log.
	 *
	 * @return the create date of this visit counter log
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this visit counter log.
	 *
	 * @param createDate the create date of this visit counter log
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this visit counter log.
	 *
	 * @return the modified date of this visit counter log
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this visit counter log.
	 *
	 * @param modifiedDate the modified date of this visit counter log
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the hit counter of this visit counter log.
	 *
	 * @return the hit counter of this visit counter log
	 */
	public int getHitCounter();

	/**
	 * Sets the hit counter of this visit counter log.
	 *
	 * @param hitCounter the hit counter of this visit counter log
	 */
	public void setHitCounter(int hitCounter);

	/**
	 * Returns the last access page ID of this visit counter log.
	 *
	 * @return the last access page ID of this visit counter log
	 */
	public long getLastAccessPageId();

	/**
	 * Sets the last access page ID of this visit counter log.
	 *
	 * @param lastAccessPageId the last access page ID of this visit counter log
	 */
	public void setLastAccessPageId(long lastAccessPageId);

	/**
	 * Returns the last access date of this visit counter log.
	 *
	 * @return the last access date of this visit counter log
	 */
	public Date getLastAccessDate();

	/**
	 * Sets the last access date of this visit counter log.
	 *
	 * @param lastAccessDate the last access date of this visit counter log
	 */
	public void setLastAccessDate(Date lastAccessDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.liferay.viettel.portal.visitcounter.model.VisitCounterLog visitCounterLog);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.viettel.portal.visitcounter.model.VisitCounterLog> toCacheModel();

	@Override
	public com.liferay.viettel.portal.visitcounter.model.VisitCounterLog toEscapedModel();

	@Override
	public com.liferay.viettel.portal.visitcounter.model.VisitCounterLog toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}