/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.liferay.viettel.portal.counter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CounterReport service. Represents a row in the &quot;CounterReport&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.viettel.portal.counter.model.impl.CounterReportModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.viettel.portal.counter.model.impl.CounterReportImpl}.
 * </p>
 *
 * @author chuchv
 * @see CounterReport
 * @see com.liferay.viettel.portal.counter.model.impl.CounterReportImpl
 * @see com.liferay.viettel.portal.counter.model.impl.CounterReportModelImpl
 * @generated
 */
public interface CounterReportModel extends BaseModel<CounterReport> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a counter report model instance should use the {@link CounterReport} interface instead.
	 */

	/**
	 * Returns the primary key of this counter report.
	 *
	 * @return the primary key of this counter report
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this counter report.
	 *
	 * @param primaryKey the primary key of this counter report
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the report ID of this counter report.
	 *
	 * @return the report ID of this counter report
	 */
	public long getReportId();

	/**
	 * Sets the report ID of this counter report.
	 *
	 * @param reportId the report ID of this counter report
	 */
	public void setReportId(long reportId);

	/**
	 * Returns the company ID of this counter report.
	 *
	 * @return the company ID of this counter report
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this counter report.
	 *
	 * @param companyId the company ID of this counter report
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this counter report.
	 *
	 * @return the group ID of this counter report
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this counter report.
	 *
	 * @param groupId the group ID of this counter report
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this counter report.
	 *
	 * @return the user ID of this counter report
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this counter report.
	 *
	 * @param userId the user ID of this counter report
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this counter report.
	 *
	 * @return the user uuid of this counter report
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this counter report.
	 *
	 * @param userUuid the user uuid of this counter report
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this counter report.
	 *
	 * @return the user name of this counter report
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this counter report.
	 *
	 * @param userName the user name of this counter report
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this counter report.
	 *
	 * @return the create date of this counter report
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this counter report.
	 *
	 * @param createDate the create date of this counter report
	 */
	public void setCreateDate(Date createDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.liferay.viettel.portal.counter.model.CounterReport counterReport);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.viettel.portal.counter.model.CounterReport> toCacheModel();

	@Override
	public com.liferay.viettel.portal.counter.model.CounterReport toEscapedModel();

	@Override
	public com.liferay.viettel.portal.counter.model.CounterReport toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}