/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.vcms.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.viettel.portal.vcms.model.Legal_Comment;
import com.viettel.portal.vcms.service.Legal_CommentLocalServiceUtil;

/**
 * The extended model base implementation for the Legal_Comment service. Represents a row in the &quot;Comment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Legal_CommentImpl}.
 * </p>
 *
 * @author chuchv
 * @see Legal_CommentImpl
 * @see com.viettel.portal.vcms.model.Legal_Comment
 * @generated
 */
public abstract class Legal_CommentBaseImpl extends Legal_CommentModelImpl
	implements Legal_Comment {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a legal_ comment model instance should use the {@link Legal_Comment} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			Legal_CommentLocalServiceUtil.addLegal_Comment(this);
		}
		else {
			Legal_CommentLocalServiceUtil.updateLegal_Comment(this);
		}
	}
}