/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.revotech.portal.videolibrary.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.revotech.portal.videolibrary.model.VLVideo;
import com.revotech.portal.videolibrary.service.VLVideoLocalServiceUtil;

/**
 * The extended model base implementation for the VLVideo service. Represents a row in the &quot;portal_video&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VLVideoImpl}.
 * </p>
 *
 * @author ChucHV
 * @see VLVideoImpl
 * @see com.revotech.portal.videolibrary.model.VLVideo
 * @generated
 */
public abstract class VLVideoBaseImpl extends VLVideoModelImpl
	implements VLVideo {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a v l video model instance should use the {@link VLVideo} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			VLVideoLocalServiceUtil.addVLVideo(this);
		}
		else {
			VLVideoLocalServiceUtil.updateVLVideo(this);
		}
	}
}