/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.revotech.portal.videolibrary.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.revotech.portal.videolibrary.model.VLVideoTag;
import com.revotech.portal.videolibrary.model.VLVideoTagModel;
import com.revotech.portal.videolibrary.model.VLVideoTagSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the VLVideoTag service. Represents a row in the &quot;portal_videotag&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.revotech.portal.videolibrary.model.VLVideoTagModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VLVideoTagImpl}.
 * </p>
 *
 * @author ChucHV
 * @see VLVideoTagImpl
 * @see com.revotech.portal.videolibrary.model.VLVideoTag
 * @see com.revotech.portal.videolibrary.model.VLVideoTagModel
 * @generated
 */
@JSON(strict = true)
public class VLVideoTagModelImpl extends BaseModelImpl<VLVideoTag>
	implements VLVideoTagModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a v l video tag model instance should use the {@link com.revotech.portal.videolibrary.model.VLVideoTag} interface instead.
	 */
	public static final String TABLE_NAME = "portal_videotag";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "videoId", Types.BIGINT },
			{ "tagId", Types.BIGINT },
			{ "groupId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table portal_videotag (id_ LONG not null primary key,videoId LONG,tagId LONG,groupId LONG)";
	public static final String TABLE_SQL_DROP = "drop table portal_videotag";
	public static final String ORDER_BY_JPQL = " ORDER BY vlVideoTag.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY portal_videotag.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.revotech.portal.videolibrary.model.VLVideoTag"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.revotech.portal.videolibrary.model.VLVideoTag"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.revotech.portal.videolibrary.model.VLVideoTag"),
			true);
	public static long GROUPID_COLUMN_BITMASK = 1L;
	public static long TAGID_COLUMN_BITMASK = 2L;
	public static long VIDEOID_COLUMN_BITMASK = 4L;
	public static long ID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static VLVideoTag toModel(VLVideoTagSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		VLVideoTag model = new VLVideoTagImpl();

		model.setId(soapModel.getId());
		model.setVideoId(soapModel.getVideoId());
		model.setTagId(soapModel.getTagId());
		model.setGroupId(soapModel.getGroupId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<VLVideoTag> toModels(VLVideoTagSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<VLVideoTag> models = new ArrayList<VLVideoTag>(soapModels.length);

		for (VLVideoTagSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.revotech.portal.videolibrary.model.VLVideoTag"));

	public VLVideoTagModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return VLVideoTag.class;
	}

	@Override
	public String getModelClassName() {
		return VLVideoTag.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("videoId", getVideoId());
		attributes.put("tagId", getTagId());
		attributes.put("groupId", getGroupId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long videoId = (Long)attributes.get("videoId");

		if (videoId != null) {
			setVideoId(videoId);
		}

		Long tagId = (Long)attributes.get("tagId");

		if (tagId != null) {
			setTagId(tagId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public long getVideoId() {
		return _videoId;
	}

	@Override
	public void setVideoId(long videoId) {
		_columnBitmask |= VIDEOID_COLUMN_BITMASK;

		if (!_setOriginalVideoId) {
			_setOriginalVideoId = true;

			_originalVideoId = _videoId;
		}

		_videoId = videoId;
	}

	public long getOriginalVideoId() {
		return _originalVideoId;
	}

	@JSON
	@Override
	public long getTagId() {
		return _tagId;
	}

	@Override
	public void setTagId(long tagId) {
		_columnBitmask |= TAGID_COLUMN_BITMASK;

		if (!_setOriginalTagId) {
			_setOriginalTagId = true;

			_originalTagId = _tagId;
		}

		_tagId = tagId;
	}

	public long getOriginalTagId() {
		return _originalTagId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			VLVideoTag.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public VLVideoTag toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VLVideoTag)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VLVideoTagImpl vlVideoTagImpl = new VLVideoTagImpl();

		vlVideoTagImpl.setId(getId());
		vlVideoTagImpl.setVideoId(getVideoId());
		vlVideoTagImpl.setTagId(getTagId());
		vlVideoTagImpl.setGroupId(getGroupId());

		vlVideoTagImpl.resetOriginalValues();

		return vlVideoTagImpl;
	}

	@Override
	public int compareTo(VLVideoTag vlVideoTag) {
		long primaryKey = vlVideoTag.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VLVideoTag)) {
			return false;
		}

		VLVideoTag vlVideoTag = (VLVideoTag)obj;

		long primaryKey = vlVideoTag.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		VLVideoTagModelImpl vlVideoTagModelImpl = this;

		vlVideoTagModelImpl._originalVideoId = vlVideoTagModelImpl._videoId;

		vlVideoTagModelImpl._setOriginalVideoId = false;

		vlVideoTagModelImpl._originalTagId = vlVideoTagModelImpl._tagId;

		vlVideoTagModelImpl._setOriginalTagId = false;

		vlVideoTagModelImpl._originalGroupId = vlVideoTagModelImpl._groupId;

		vlVideoTagModelImpl._setOriginalGroupId = false;

		vlVideoTagModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<VLVideoTag> toCacheModel() {
		VLVideoTagCacheModel vlVideoTagCacheModel = new VLVideoTagCacheModel();

		vlVideoTagCacheModel.id = getId();

		vlVideoTagCacheModel.videoId = getVideoId();

		vlVideoTagCacheModel.tagId = getTagId();

		vlVideoTagCacheModel.groupId = getGroupId();

		return vlVideoTagCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", videoId=");
		sb.append(getVideoId());
		sb.append(", tagId=");
		sb.append(getTagId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.revotech.portal.videolibrary.model.VLVideoTag");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>videoId</column-name><column-value><![CDATA[");
		sb.append(getVideoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tagId</column-name><column-value><![CDATA[");
		sb.append(getTagId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = VLVideoTag.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			VLVideoTag.class
		};
	private long _id;
	private long _videoId;
	private long _originalVideoId;
	private boolean _setOriginalVideoId;
	private long _tagId;
	private long _originalTagId;
	private boolean _setOriginalTagId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _columnBitmask;
	private VLVideoTag _escapedModel;
}