/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.thongke.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.viettel.portal.thongke.model.BaiVietNhuanBut;
import com.viettel.portal.thongke.model.BaiVietNhuanButModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the BaiVietNhuanBut service. Represents a row in the &quot;portal_baivietnhuanbut&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.viettel.portal.thongke.model.BaiVietNhuanButModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BaiVietNhuanButImpl}.
 * </p>
 *
 * @author lamvn
 * @see BaiVietNhuanButImpl
 * @see com.viettel.portal.thongke.model.BaiVietNhuanBut
 * @see com.viettel.portal.thongke.model.BaiVietNhuanButModel
 * @generated
 */
public class BaiVietNhuanButModelImpl extends BaseModelImpl<BaiVietNhuanBut>
	implements BaiVietNhuanButModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bai viet nhuan but model instance should use the {@link com.viettel.portal.thongke.model.BaiVietNhuanBut} interface instead.
	 */
	public static final String TABLE_NAME = "portal_baivietnhuanbut";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "baiVietId", Types.BIGINT },
			{ "loaiBaiViet", Types.INTEGER },
			{ "tieuDe", Types.VARCHAR },
			{ "tacGia", Types.VARCHAR },
			{ "diaChi", Types.VARCHAR },
			{ "ngayXuatBan", Types.TIMESTAMP },
			{ "rating", Types.VARCHAR },
			{ "ratingValue", Types.DOUBLE },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifyDate", Types.TIMESTAMP },
			{ "userName", Types.VARCHAR },
			{ "userId", Types.BIGINT },
			{ "type_", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table portal_baivietnhuanbut (id_ LONG not null primary key,baiVietId LONG,loaiBaiViet INTEGER,tieuDe VARCHAR(1000) null,tacGia VARCHAR(1000) null,diaChi VARCHAR(1000) null,ngayXuatBan DATE null,rating VARCHAR(75) null,ratingValue DOUBLE,companyId LONG,groupId LONG,createDate DATE null,modifyDate DATE null,userName VARCHAR(75) null,userId LONG,type_ INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table portal_baivietnhuanbut";
	public static final String ORDER_BY_JPQL = " ORDER BY baiVietNhuanBut.createDate DESC, baiVietNhuanBut.tieuDe ASC";
	public static final String ORDER_BY_SQL = " ORDER BY portal_baivietnhuanbut.createDate DESC, portal_baivietnhuanbut.tieuDe ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.viettel.portal.thongke.model.BaiVietNhuanBut"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.viettel.portal.thongke.model.BaiVietNhuanBut"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.viettel.portal.thongke.model.BaiVietNhuanBut"),
			true);
	public static long BAIVIETID_COLUMN_BITMASK = 1L;
	public static long GROUPID_COLUMN_BITMASK = 2L;
	public static long TYPE_COLUMN_BITMASK = 4L;
	public static long CREATEDATE_COLUMN_BITMASK = 8L;
	public static long TIEUDE_COLUMN_BITMASK = 16L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.viettel.portal.thongke.model.BaiVietNhuanBut"));

	public BaiVietNhuanButModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BaiVietNhuanBut.class;
	}

	@Override
	public String getModelClassName() {
		return BaiVietNhuanBut.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("baiVietId", getBaiVietId());
		attributes.put("loaiBaiViet", getLoaiBaiViet());
		attributes.put("tieuDe", getTieuDe());
		attributes.put("tacGia", getTacGia());
		attributes.put("diaChi", getDiaChi());
		attributes.put("ngayXuatBan", getNgayXuatBan());
		attributes.put("rating", getRating());
		attributes.put("ratingValue", getRatingValue());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifyDate", getModifyDate());
		attributes.put("userName", getUserName());
		attributes.put("userId", getUserId());
		attributes.put("type", getType());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long baiVietId = (Long)attributes.get("baiVietId");

		if (baiVietId != null) {
			setBaiVietId(baiVietId);
		}

		Integer loaiBaiViet = (Integer)attributes.get("loaiBaiViet");

		if (loaiBaiViet != null) {
			setLoaiBaiViet(loaiBaiViet);
		}

		String tieuDe = (String)attributes.get("tieuDe");

		if (tieuDe != null) {
			setTieuDe(tieuDe);
		}

		String tacGia = (String)attributes.get("tacGia");

		if (tacGia != null) {
			setTacGia(tacGia);
		}

		String diaChi = (String)attributes.get("diaChi");

		if (diaChi != null) {
			setDiaChi(diaChi);
		}

		Date ngayXuatBan = (Date)attributes.get("ngayXuatBan");

		if (ngayXuatBan != null) {
			setNgayXuatBan(ngayXuatBan);
		}

		String rating = (String)attributes.get("rating");

		if (rating != null) {
			setRating(rating);
		}

		Double ratingValue = (Double)attributes.get("ratingValue");

		if (ratingValue != null) {
			setRatingValue(ratingValue);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifyDate = (Date)attributes.get("modifyDate");

		if (modifyDate != null) {
			setModifyDate(modifyDate);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Integer type = (Integer)attributes.get("type");

		if (type != null) {
			setType(type);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public long getBaiVietId() {
		return _baiVietId;
	}

	@Override
	public void setBaiVietId(long baiVietId) {
		_columnBitmask |= BAIVIETID_COLUMN_BITMASK;

		if (!_setOriginalBaiVietId) {
			_setOriginalBaiVietId = true;

			_originalBaiVietId = _baiVietId;
		}

		_baiVietId = baiVietId;
	}

	public long getOriginalBaiVietId() {
		return _originalBaiVietId;
	}

	@Override
	public int getLoaiBaiViet() {
		return _loaiBaiViet;
	}

	@Override
	public void setLoaiBaiViet(int loaiBaiViet) {
		_loaiBaiViet = loaiBaiViet;
	}

	@Override
	public String getTieuDe() {
		if (_tieuDe == null) {
			return StringPool.BLANK;
		}
		else {
			return _tieuDe;
		}
	}

	@Override
	public void setTieuDe(String tieuDe) {
		_columnBitmask = -1L;

		_tieuDe = tieuDe;
	}

	@Override
	public String getTacGia() {
		if (_tacGia == null) {
			return StringPool.BLANK;
		}
		else {
			return _tacGia;
		}
	}

	@Override
	public void setTacGia(String tacGia) {
		_tacGia = tacGia;
	}

	@Override
	public String getDiaChi() {
		if (_diaChi == null) {
			return StringPool.BLANK;
		}
		else {
			return _diaChi;
		}
	}

	@Override
	public void setDiaChi(String diaChi) {
		_diaChi = diaChi;
	}

	@Override
	public Date getNgayXuatBan() {
		return _ngayXuatBan;
	}

	@Override
	public void setNgayXuatBan(Date ngayXuatBan) {
		_ngayXuatBan = ngayXuatBan;
	}

	@Override
	public String getRating() {
		if (_rating == null) {
			return StringPool.BLANK;
		}
		else {
			return _rating;
		}
	}

	@Override
	public void setRating(String rating) {
		_rating = rating;
	}

	@Override
	public double getRatingValue() {
		return _ratingValue;
	}

	@Override
	public void setRatingValue(double ratingValue) {
		_ratingValue = ratingValue;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@Override
	public Date getModifyDate() {
		return _modifyDate;
	}

	@Override
	public void setModifyDate(Date modifyDate) {
		_modifyDate = modifyDate;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		_columnBitmask |= TYPE_COLUMN_BITMASK;

		if (!_setOriginalType) {
			_setOriginalType = true;

			_originalType = _type;
		}

		_type = type;
	}

	public int getOriginalType() {
		return _originalType;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			BaiVietNhuanBut.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BaiVietNhuanBut toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (BaiVietNhuanBut)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BaiVietNhuanButImpl baiVietNhuanButImpl = new BaiVietNhuanButImpl();

		baiVietNhuanButImpl.setId(getId());
		baiVietNhuanButImpl.setBaiVietId(getBaiVietId());
		baiVietNhuanButImpl.setLoaiBaiViet(getLoaiBaiViet());
		baiVietNhuanButImpl.setTieuDe(getTieuDe());
		baiVietNhuanButImpl.setTacGia(getTacGia());
		baiVietNhuanButImpl.setDiaChi(getDiaChi());
		baiVietNhuanButImpl.setNgayXuatBan(getNgayXuatBan());
		baiVietNhuanButImpl.setRating(getRating());
		baiVietNhuanButImpl.setRatingValue(getRatingValue());
		baiVietNhuanButImpl.setCompanyId(getCompanyId());
		baiVietNhuanButImpl.setGroupId(getGroupId());
		baiVietNhuanButImpl.setCreateDate(getCreateDate());
		baiVietNhuanButImpl.setModifyDate(getModifyDate());
		baiVietNhuanButImpl.setUserName(getUserName());
		baiVietNhuanButImpl.setUserId(getUserId());
		baiVietNhuanButImpl.setType(getType());

		baiVietNhuanButImpl.resetOriginalValues();

		return baiVietNhuanButImpl;
	}

	@Override
	public int compareTo(BaiVietNhuanBut baiVietNhuanBut) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(),
				baiVietNhuanBut.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		value = getTieuDe().compareTo(baiVietNhuanBut.getTieuDe());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof BaiVietNhuanBut)) {
			return false;
		}

		BaiVietNhuanBut baiVietNhuanBut = (BaiVietNhuanBut)obj;

		long primaryKey = baiVietNhuanBut.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		BaiVietNhuanButModelImpl baiVietNhuanButModelImpl = this;

		baiVietNhuanButModelImpl._originalBaiVietId = baiVietNhuanButModelImpl._baiVietId;

		baiVietNhuanButModelImpl._setOriginalBaiVietId = false;

		baiVietNhuanButModelImpl._originalGroupId = baiVietNhuanButModelImpl._groupId;

		baiVietNhuanButModelImpl._setOriginalGroupId = false;

		baiVietNhuanButModelImpl._originalType = baiVietNhuanButModelImpl._type;

		baiVietNhuanButModelImpl._setOriginalType = false;

		baiVietNhuanButModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<BaiVietNhuanBut> toCacheModel() {
		BaiVietNhuanButCacheModel baiVietNhuanButCacheModel = new BaiVietNhuanButCacheModel();

		baiVietNhuanButCacheModel.id = getId();

		baiVietNhuanButCacheModel.baiVietId = getBaiVietId();

		baiVietNhuanButCacheModel.loaiBaiViet = getLoaiBaiViet();

		baiVietNhuanButCacheModel.tieuDe = getTieuDe();

		String tieuDe = baiVietNhuanButCacheModel.tieuDe;

		if ((tieuDe != null) && (tieuDe.length() == 0)) {
			baiVietNhuanButCacheModel.tieuDe = null;
		}

		baiVietNhuanButCacheModel.tacGia = getTacGia();

		String tacGia = baiVietNhuanButCacheModel.tacGia;

		if ((tacGia != null) && (tacGia.length() == 0)) {
			baiVietNhuanButCacheModel.tacGia = null;
		}

		baiVietNhuanButCacheModel.diaChi = getDiaChi();

		String diaChi = baiVietNhuanButCacheModel.diaChi;

		if ((diaChi != null) && (diaChi.length() == 0)) {
			baiVietNhuanButCacheModel.diaChi = null;
		}

		Date ngayXuatBan = getNgayXuatBan();

		if (ngayXuatBan != null) {
			baiVietNhuanButCacheModel.ngayXuatBan = ngayXuatBan.getTime();
		}
		else {
			baiVietNhuanButCacheModel.ngayXuatBan = Long.MIN_VALUE;
		}

		baiVietNhuanButCacheModel.rating = getRating();

		String rating = baiVietNhuanButCacheModel.rating;

		if ((rating != null) && (rating.length() == 0)) {
			baiVietNhuanButCacheModel.rating = null;
		}

		baiVietNhuanButCacheModel.ratingValue = getRatingValue();

		baiVietNhuanButCacheModel.companyId = getCompanyId();

		baiVietNhuanButCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			baiVietNhuanButCacheModel.createDate = createDate.getTime();
		}
		else {
			baiVietNhuanButCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifyDate = getModifyDate();

		if (modifyDate != null) {
			baiVietNhuanButCacheModel.modifyDate = modifyDate.getTime();
		}
		else {
			baiVietNhuanButCacheModel.modifyDate = Long.MIN_VALUE;
		}

		baiVietNhuanButCacheModel.userName = getUserName();

		String userName = baiVietNhuanButCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			baiVietNhuanButCacheModel.userName = null;
		}

		baiVietNhuanButCacheModel.userId = getUserId();

		baiVietNhuanButCacheModel.type = getType();

		return baiVietNhuanButCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(33);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", baiVietId=");
		sb.append(getBaiVietId());
		sb.append(", loaiBaiViet=");
		sb.append(getLoaiBaiViet());
		sb.append(", tieuDe=");
		sb.append(getTieuDe());
		sb.append(", tacGia=");
		sb.append(getTacGia());
		sb.append(", diaChi=");
		sb.append(getDiaChi());
		sb.append(", ngayXuatBan=");
		sb.append(getNgayXuatBan());
		sb.append(", rating=");
		sb.append(getRating());
		sb.append(", ratingValue=");
		sb.append(getRatingValue());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifyDate=");
		sb.append(getModifyDate());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", type=");
		sb.append(getType());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(52);

		sb.append("<model><model-name>");
		sb.append("com.viettel.portal.thongke.model.BaiVietNhuanBut");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>baiVietId</column-name><column-value><![CDATA[");
		sb.append(getBaiVietId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiBaiViet</column-name><column-value><![CDATA[");
		sb.append(getLoaiBaiViet());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tieuDe</column-name><column-value><![CDATA[");
		sb.append(getTieuDe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tacGia</column-name><column-value><![CDATA[");
		sb.append(getTacGia());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChi</column-name><column-value><![CDATA[");
		sb.append(getDiaChi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayXuatBan</column-name><column-value><![CDATA[");
		sb.append(getNgayXuatBan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rating</column-name><column-value><![CDATA[");
		sb.append(getRating());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ratingValue</column-name><column-value><![CDATA[");
		sb.append(getRatingValue());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifyDate</column-name><column-value><![CDATA[");
		sb.append(getModifyDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = BaiVietNhuanBut.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			BaiVietNhuanBut.class
		};
	private long _id;
	private long _baiVietId;
	private long _originalBaiVietId;
	private boolean _setOriginalBaiVietId;
	private int _loaiBaiViet;
	private String _tieuDe;
	private String _tacGia;
	private String _diaChi;
	private Date _ngayXuatBan;
	private String _rating;
	private double _ratingValue;
	private long _companyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private Date _createDate;
	private Date _modifyDate;
	private String _userName;
	private long _userId;
	private String _userUuid;
	private int _type;
	private int _originalType;
	private boolean _setOriginalType;
	private long _columnBitmask;
	private BaiVietNhuanBut _escapedModel;
}