/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.thongke.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.viettel.portal.thongke.model.ContentProfit;
import com.viettel.portal.thongke.service.ContentProfitLocalServiceUtil;

/**
 * The extended model base implementation for the ContentProfit service. Represents a row in the &quot;vcms_Content_Profit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContentProfitImpl}.
 * </p>
 *
 * @author lamvn
 * @see ContentProfitImpl
 * @see com.viettel.portal.thongke.model.ContentProfit
 * @generated
 */
public abstract class ContentProfitBaseImpl extends ContentProfitModelImpl
	implements ContentProfit {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a content profit model instance should use the {@link ContentProfit} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			ContentProfitLocalServiceUtil.addContentProfit(this);
		}
		else {
			ContentProfitLocalServiceUtil.updateContentProfit(this);
		}
	}
}