/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.thongke.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.viettel.portal.thongke.model.PhongBanNhuanBut;
import com.viettel.portal.thongke.model.PhongBanNhuanButModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the PhongBanNhuanBut service. Represents a row in the &quot;portal_phongbannhuanbut&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.viettel.portal.thongke.model.PhongBanNhuanButModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PhongBanNhuanButImpl}.
 * </p>
 *
 * @author lamvn
 * @see PhongBanNhuanButImpl
 * @see com.viettel.portal.thongke.model.PhongBanNhuanBut
 * @see com.viettel.portal.thongke.model.PhongBanNhuanButModel
 * @generated
 */
public class PhongBanNhuanButModelImpl extends BaseModelImpl<PhongBanNhuanBut>
	implements PhongBanNhuanButModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a phong ban nhuan but model instance should use the {@link com.viettel.portal.thongke.model.PhongBanNhuanBut} interface instead.
	 */
	public static final String TABLE_NAME = "portal_phongbannhuanbut";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "caption", Types.VARCHAR },
			{ "fromDate", Types.TIMESTAMP },
			{ "toDate", Types.TIMESTAMP },
			{ "status", Types.BOOLEAN },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifyDate", Types.TIMESTAMP },
			{ "userName", Types.VARCHAR },
			{ "userId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table portal_phongbannhuanbut (id_ LONG not null primary key,caption VARCHAR(1000) null,fromDate DATE null,toDate DATE null,status BOOLEAN,companyId LONG,groupId LONG,createDate DATE null,modifyDate DATE null,userName VARCHAR(75) null,userId LONG)";
	public static final String TABLE_SQL_DROP = "drop table portal_phongbannhuanbut";
	public static final String ORDER_BY_JPQL = " ORDER BY phongBanNhuanBut.createDate DESC, phongBanNhuanBut.caption ASC";
	public static final String ORDER_BY_SQL = " ORDER BY portal_phongbannhuanbut.createDate DESC, portal_phongbannhuanbut.caption ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.viettel.portal.thongke.model.PhongBanNhuanBut"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.viettel.portal.thongke.model.PhongBanNhuanBut"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.viettel.portal.thongke.model.PhongBanNhuanBut"),
			true);
	public static long CAPTION_COLUMN_BITMASK = 1L;
	public static long GROUPID_COLUMN_BITMASK = 2L;
	public static long STATUS_COLUMN_BITMASK = 4L;
	public static long CREATEDATE_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.viettel.portal.thongke.model.PhongBanNhuanBut"));

	public PhongBanNhuanButModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PhongBanNhuanBut.class;
	}

	@Override
	public String getModelClassName() {
		return PhongBanNhuanBut.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("caption", getCaption());
		attributes.put("fromDate", getFromDate());
		attributes.put("toDate", getToDate());
		attributes.put("status", getStatus());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifyDate", getModifyDate());
		attributes.put("userName", getUserName());
		attributes.put("userId", getUserId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String caption = (String)attributes.get("caption");

		if (caption != null) {
			setCaption(caption);
		}

		Date fromDate = (Date)attributes.get("fromDate");

		if (fromDate != null) {
			setFromDate(fromDate);
		}

		Date toDate = (Date)attributes.get("toDate");

		if (toDate != null) {
			setToDate(toDate);
		}

		Boolean status = (Boolean)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifyDate = (Date)attributes.get("modifyDate");

		if (modifyDate != null) {
			setModifyDate(modifyDate);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public String getCaption() {
		if (_caption == null) {
			return StringPool.BLANK;
		}
		else {
			return _caption;
		}
	}

	@Override
	public void setCaption(String caption) {
		_columnBitmask = -1L;

		if (_originalCaption == null) {
			_originalCaption = _caption;
		}

		_caption = caption;
	}

	public String getOriginalCaption() {
		return GetterUtil.getString(_originalCaption);
	}

	@Override
	public Date getFromDate() {
		return _fromDate;
	}

	@Override
	public void setFromDate(Date fromDate) {
		_fromDate = fromDate;
	}

	@Override
	public Date getToDate() {
		return _toDate;
	}

	@Override
	public void setToDate(Date toDate) {
		_toDate = toDate;
	}

	@Override
	public boolean getStatus() {
		return _status;
	}

	@Override
	public boolean isStatus() {
		return _status;
	}

	@Override
	public void setStatus(boolean status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public boolean getOriginalStatus() {
		return _originalStatus;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@Override
	public Date getModifyDate() {
		return _modifyDate;
	}

	@Override
	public void setModifyDate(Date modifyDate) {
		_modifyDate = modifyDate;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			PhongBanNhuanBut.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PhongBanNhuanBut toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PhongBanNhuanBut)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PhongBanNhuanButImpl phongBanNhuanButImpl = new PhongBanNhuanButImpl();

		phongBanNhuanButImpl.setId(getId());
		phongBanNhuanButImpl.setCaption(getCaption());
		phongBanNhuanButImpl.setFromDate(getFromDate());
		phongBanNhuanButImpl.setToDate(getToDate());
		phongBanNhuanButImpl.setStatus(getStatus());
		phongBanNhuanButImpl.setCompanyId(getCompanyId());
		phongBanNhuanButImpl.setGroupId(getGroupId());
		phongBanNhuanButImpl.setCreateDate(getCreateDate());
		phongBanNhuanButImpl.setModifyDate(getModifyDate());
		phongBanNhuanButImpl.setUserName(getUserName());
		phongBanNhuanButImpl.setUserId(getUserId());

		phongBanNhuanButImpl.resetOriginalValues();

		return phongBanNhuanButImpl;
	}

	@Override
	public int compareTo(PhongBanNhuanBut phongBanNhuanBut) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(),
				phongBanNhuanBut.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		value = getCaption().compareTo(phongBanNhuanBut.getCaption());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PhongBanNhuanBut)) {
			return false;
		}

		PhongBanNhuanBut phongBanNhuanBut = (PhongBanNhuanBut)obj;

		long primaryKey = phongBanNhuanBut.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		PhongBanNhuanButModelImpl phongBanNhuanButModelImpl = this;

		phongBanNhuanButModelImpl._originalCaption = phongBanNhuanButModelImpl._caption;

		phongBanNhuanButModelImpl._originalStatus = phongBanNhuanButModelImpl._status;

		phongBanNhuanButModelImpl._setOriginalStatus = false;

		phongBanNhuanButModelImpl._originalGroupId = phongBanNhuanButModelImpl._groupId;

		phongBanNhuanButModelImpl._setOriginalGroupId = false;

		phongBanNhuanButModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<PhongBanNhuanBut> toCacheModel() {
		PhongBanNhuanButCacheModel phongBanNhuanButCacheModel = new PhongBanNhuanButCacheModel();

		phongBanNhuanButCacheModel.id = getId();

		phongBanNhuanButCacheModel.caption = getCaption();

		String caption = phongBanNhuanButCacheModel.caption;

		if ((caption != null) && (caption.length() == 0)) {
			phongBanNhuanButCacheModel.caption = null;
		}

		Date fromDate = getFromDate();

		if (fromDate != null) {
			phongBanNhuanButCacheModel.fromDate = fromDate.getTime();
		}
		else {
			phongBanNhuanButCacheModel.fromDate = Long.MIN_VALUE;
		}

		Date toDate = getToDate();

		if (toDate != null) {
			phongBanNhuanButCacheModel.toDate = toDate.getTime();
		}
		else {
			phongBanNhuanButCacheModel.toDate = Long.MIN_VALUE;
		}

		phongBanNhuanButCacheModel.status = getStatus();

		phongBanNhuanButCacheModel.companyId = getCompanyId();

		phongBanNhuanButCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			phongBanNhuanButCacheModel.createDate = createDate.getTime();
		}
		else {
			phongBanNhuanButCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifyDate = getModifyDate();

		if (modifyDate != null) {
			phongBanNhuanButCacheModel.modifyDate = modifyDate.getTime();
		}
		else {
			phongBanNhuanButCacheModel.modifyDate = Long.MIN_VALUE;
		}

		phongBanNhuanButCacheModel.userName = getUserName();

		String userName = phongBanNhuanButCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			phongBanNhuanButCacheModel.userName = null;
		}

		phongBanNhuanButCacheModel.userId = getUserId();

		return phongBanNhuanButCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", caption=");
		sb.append(getCaption());
		sb.append(", fromDate=");
		sb.append(getFromDate());
		sb.append(", toDate=");
		sb.append(getToDate());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifyDate=");
		sb.append(getModifyDate());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.viettel.portal.thongke.model.PhongBanNhuanBut");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>caption</column-name><column-value><![CDATA[");
		sb.append(getCaption());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fromDate</column-name><column-value><![CDATA[");
		sb.append(getFromDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>toDate</column-name><column-value><![CDATA[");
		sb.append(getToDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifyDate</column-name><column-value><![CDATA[");
		sb.append(getModifyDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PhongBanNhuanBut.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			PhongBanNhuanBut.class
		};
	private long _id;
	private String _caption;
	private String _originalCaption;
	private Date _fromDate;
	private Date _toDate;
	private boolean _status;
	private boolean _originalStatus;
	private boolean _setOriginalStatus;
	private long _companyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private Date _createDate;
	private Date _modifyDate;
	private String _userName;
	private long _userId;
	private String _userUuid;
	private long _columnBitmask;
	private PhongBanNhuanBut _escapedModel;
}