/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.thongke.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.viettel.portal.thongke.model.PhongBan;
import com.viettel.portal.thongke.model.PhongBanModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the PhongBan service. Represents a row in the &quot;portal_phongban&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.viettel.portal.thongke.model.PhongBanModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PhongBanImpl}.
 * </p>
 *
 * @author lamvn
 * @see PhongBanImpl
 * @see com.viettel.portal.thongke.model.PhongBan
 * @see com.viettel.portal.thongke.model.PhongBanModel
 * @generated
 */
public class PhongBanModelImpl extends BaseModelImpl<PhongBan>
	implements PhongBanModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a phong ban model instance should use the {@link com.viettel.portal.thongke.model.PhongBan} interface instead.
	 */
	public static final String TABLE_NAME = "portal_phongban";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "order_", Types.INTEGER },
			{ "descriptions", Types.VARCHAR },
			{ "status", Types.BOOLEAN },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifyDate", Types.TIMESTAMP },
			{ "userName", Types.VARCHAR },
			{ "userId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table portal_phongban (id_ LONG not null primary key,name VARCHAR(1000) null,order_ INTEGER,descriptions STRING null,status BOOLEAN,companyId LONG,groupId LONG,createDate DATE null,modifyDate DATE null,userName VARCHAR(75) null,userId LONG)";
	public static final String TABLE_SQL_DROP = "drop table portal_phongban";
	public static final String ORDER_BY_JPQL = " ORDER BY phongBan.order_ ASC, phongBan.createDate DESC, phongBan.name ASC";
	public static final String ORDER_BY_SQL = " ORDER BY portal_phongban.order_ ASC, portal_phongban.createDate DESC, portal_phongban.name ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.viettel.portal.thongke.model.PhongBan"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.viettel.portal.thongke.model.PhongBan"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.viettel.portal.thongke.model.PhongBan"),
			true);
	public static long GROUPID_COLUMN_BITMASK = 1L;
	public static long NAME_COLUMN_BITMASK = 2L;
	public static long STATUS_COLUMN_BITMASK = 4L;
	public static long ORDER__COLUMN_BITMASK = 8L;
	public static long CREATEDATE_COLUMN_BITMASK = 16L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.viettel.portal.thongke.model.PhongBan"));

	public PhongBanModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PhongBan.class;
	}

	@Override
	public String getModelClassName() {
		return PhongBan.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("name", getName());
		attributes.put("order_", getOrder_());
		attributes.put("descriptions", getDescriptions());
		attributes.put("status", getStatus());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifyDate", getModifyDate());
		attributes.put("userName", getUserName());
		attributes.put("userId", getUserId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		Integer order_ = (Integer)attributes.get("order_");

		if (order_ != null) {
			setOrder_(order_);
		}

		String descriptions = (String)attributes.get("descriptions");

		if (descriptions != null) {
			setDescriptions(descriptions);
		}

		Boolean status = (Boolean)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifyDate = (Date)attributes.get("modifyDate");

		if (modifyDate != null) {
			setModifyDate(modifyDate);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask = -1L;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@Override
	public int getOrder_() {
		return _order_;
	}

	@Override
	public void setOrder_(int order_) {
		_columnBitmask = -1L;

		_order_ = order_;
	}

	@Override
	public String getDescriptions() {
		if (_descriptions == null) {
			return StringPool.BLANK;
		}
		else {
			return _descriptions;
		}
	}

	@Override
	public void setDescriptions(String descriptions) {
		_descriptions = descriptions;
	}

	@Override
	public boolean getStatus() {
		return _status;
	}

	@Override
	public boolean isStatus() {
		return _status;
	}

	@Override
	public void setStatus(boolean status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public boolean getOriginalStatus() {
		return _originalStatus;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@Override
	public Date getModifyDate() {
		return _modifyDate;
	}

	@Override
	public void setModifyDate(Date modifyDate) {
		_modifyDate = modifyDate;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			PhongBan.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PhongBan toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PhongBan)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PhongBanImpl phongBanImpl = new PhongBanImpl();

		phongBanImpl.setId(getId());
		phongBanImpl.setName(getName());
		phongBanImpl.setOrder_(getOrder_());
		phongBanImpl.setDescriptions(getDescriptions());
		phongBanImpl.setStatus(getStatus());
		phongBanImpl.setCompanyId(getCompanyId());
		phongBanImpl.setGroupId(getGroupId());
		phongBanImpl.setCreateDate(getCreateDate());
		phongBanImpl.setModifyDate(getModifyDate());
		phongBanImpl.setUserName(getUserName());
		phongBanImpl.setUserId(getUserId());

		phongBanImpl.resetOriginalValues();

		return phongBanImpl;
	}

	@Override
	public int compareTo(PhongBan phongBan) {
		int value = 0;

		if (getOrder_() < phongBan.getOrder_()) {
			value = -1;
		}
		else if (getOrder_() > phongBan.getOrder_()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		value = DateUtil.compareTo(getCreateDate(), phongBan.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		value = getName().compareTo(phongBan.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PhongBan)) {
			return false;
		}

		PhongBan phongBan = (PhongBan)obj;

		long primaryKey = phongBan.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		PhongBanModelImpl phongBanModelImpl = this;

		phongBanModelImpl._originalName = phongBanModelImpl._name;

		phongBanModelImpl._originalStatus = phongBanModelImpl._status;

		phongBanModelImpl._setOriginalStatus = false;

		phongBanModelImpl._originalGroupId = phongBanModelImpl._groupId;

		phongBanModelImpl._setOriginalGroupId = false;

		phongBanModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<PhongBan> toCacheModel() {
		PhongBanCacheModel phongBanCacheModel = new PhongBanCacheModel();

		phongBanCacheModel.id = getId();

		phongBanCacheModel.name = getName();

		String name = phongBanCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			phongBanCacheModel.name = null;
		}

		phongBanCacheModel.order_ = getOrder_();

		phongBanCacheModel.descriptions = getDescriptions();

		String descriptions = phongBanCacheModel.descriptions;

		if ((descriptions != null) && (descriptions.length() == 0)) {
			phongBanCacheModel.descriptions = null;
		}

		phongBanCacheModel.status = getStatus();

		phongBanCacheModel.companyId = getCompanyId();

		phongBanCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			phongBanCacheModel.createDate = createDate.getTime();
		}
		else {
			phongBanCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifyDate = getModifyDate();

		if (modifyDate != null) {
			phongBanCacheModel.modifyDate = modifyDate.getTime();
		}
		else {
			phongBanCacheModel.modifyDate = Long.MIN_VALUE;
		}

		phongBanCacheModel.userName = getUserName();

		String userName = phongBanCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			phongBanCacheModel.userName = null;
		}

		phongBanCacheModel.userId = getUserId();

		return phongBanCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", order_=");
		sb.append(getOrder_());
		sb.append(", descriptions=");
		sb.append(getDescriptions());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifyDate=");
		sb.append(getModifyDate());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.viettel.portal.thongke.model.PhongBan");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>order_</column-name><column-value><![CDATA[");
		sb.append(getOrder_());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descriptions</column-name><column-value><![CDATA[");
		sb.append(getDescriptions());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifyDate</column-name><column-value><![CDATA[");
		sb.append(getModifyDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PhongBan.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			PhongBan.class
		};
	private long _id;
	private String _name;
	private String _originalName;
	private int _order_;
	private String _descriptions;
	private boolean _status;
	private boolean _originalStatus;
	private boolean _setOriginalStatus;
	private long _companyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private Date _createDate;
	private Date _modifyDate;
	private String _userName;
	private long _userId;
	private String _userUuid;
	private long _columnBitmask;
	private PhongBan _escapedModel;
}