/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.thongke.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BaiVietNhuanBut service. Represents a row in the &quot;portal_baivietnhuanbut&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viettel.portal.thongke.model.impl.BaiVietNhuanButModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viettel.portal.thongke.model.impl.BaiVietNhuanButImpl}.
 * </p>
 *
 * @author lamvn
 * @see BaiVietNhuanBut
 * @see com.viettel.portal.thongke.model.impl.BaiVietNhuanButImpl
 * @see com.viettel.portal.thongke.model.impl.BaiVietNhuanButModelImpl
 * @generated
 */
public interface BaiVietNhuanButModel extends BaseModel<BaiVietNhuanBut> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bai viet nhuan but model instance should use the {@link BaiVietNhuanBut} interface instead.
	 */

	/**
	 * Returns the primary key of this bai viet nhuan but.
	 *
	 * @return the primary key of this bai viet nhuan but
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bai viet nhuan but.
	 *
	 * @param primaryKey the primary key of this bai viet nhuan but
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this bai viet nhuan but.
	 *
	 * @return the ID of this bai viet nhuan but
	 */
	public long getId();

	/**
	 * Sets the ID of this bai viet nhuan but.
	 *
	 * @param id the ID of this bai viet nhuan but
	 */
	public void setId(long id);

	/**
	 * Returns the bai viet ID of this bai viet nhuan but.
	 *
	 * @return the bai viet ID of this bai viet nhuan but
	 */
	public long getBaiVietId();

	/**
	 * Sets the bai viet ID of this bai viet nhuan but.
	 *
	 * @param baiVietId the bai viet ID of this bai viet nhuan but
	 */
	public void setBaiVietId(long baiVietId);

	/**
	 * Returns the loai bai viet of this bai viet nhuan but.
	 *
	 * @return the loai bai viet of this bai viet nhuan but
	 */
	public int getLoaiBaiViet();

	/**
	 * Sets the loai bai viet of this bai viet nhuan but.
	 *
	 * @param loaiBaiViet the loai bai viet of this bai viet nhuan but
	 */
	public void setLoaiBaiViet(int loaiBaiViet);

	/**
	 * Returns the tieu de of this bai viet nhuan but.
	 *
	 * @return the tieu de of this bai viet nhuan but
	 */
	@AutoEscape
	public String getTieuDe();

	/**
	 * Sets the tieu de of this bai viet nhuan but.
	 *
	 * @param tieuDe the tieu de of this bai viet nhuan but
	 */
	public void setTieuDe(String tieuDe);

	/**
	 * Returns the tac gia of this bai viet nhuan but.
	 *
	 * @return the tac gia of this bai viet nhuan but
	 */
	@AutoEscape
	public String getTacGia();

	/**
	 * Sets the tac gia of this bai viet nhuan but.
	 *
	 * @param tacGia the tac gia of this bai viet nhuan but
	 */
	public void setTacGia(String tacGia);

	/**
	 * Returns the dia chi of this bai viet nhuan but.
	 *
	 * @return the dia chi of this bai viet nhuan but
	 */
	@AutoEscape
	public String getDiaChi();

	/**
	 * Sets the dia chi of this bai viet nhuan but.
	 *
	 * @param diaChi the dia chi of this bai viet nhuan but
	 */
	public void setDiaChi(String diaChi);

	/**
	 * Returns the ngay xuat ban of this bai viet nhuan but.
	 *
	 * @return the ngay xuat ban of this bai viet nhuan but
	 */
	public Date getNgayXuatBan();

	/**
	 * Sets the ngay xuat ban of this bai viet nhuan but.
	 *
	 * @param ngayXuatBan the ngay xuat ban of this bai viet nhuan but
	 */
	public void setNgayXuatBan(Date ngayXuatBan);

	/**
	 * Returns the rating of this bai viet nhuan but.
	 *
	 * @return the rating of this bai viet nhuan but
	 */
	@AutoEscape
	public String getRating();

	/**
	 * Sets the rating of this bai viet nhuan but.
	 *
	 * @param rating the rating of this bai viet nhuan but
	 */
	public void setRating(String rating);

	/**
	 * Returns the rating value of this bai viet nhuan but.
	 *
	 * @return the rating value of this bai viet nhuan but
	 */
	public double getRatingValue();

	/**
	 * Sets the rating value of this bai viet nhuan but.
	 *
	 * @param ratingValue the rating value of this bai viet nhuan but
	 */
	public void setRatingValue(double ratingValue);

	/**
	 * Returns the company ID of this bai viet nhuan but.
	 *
	 * @return the company ID of this bai viet nhuan but
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this bai viet nhuan but.
	 *
	 * @param companyId the company ID of this bai viet nhuan but
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this bai viet nhuan but.
	 *
	 * @return the group ID of this bai viet nhuan but
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this bai viet nhuan but.
	 *
	 * @param groupId the group ID of this bai viet nhuan but
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this bai viet nhuan but.
	 *
	 * @return the create date of this bai viet nhuan but
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this bai viet nhuan but.
	 *
	 * @param createDate the create date of this bai viet nhuan but
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modify date of this bai viet nhuan but.
	 *
	 * @return the modify date of this bai viet nhuan but
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this bai viet nhuan but.
	 *
	 * @param modifyDate the modify date of this bai viet nhuan but
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the user name of this bai viet nhuan but.
	 *
	 * @return the user name of this bai viet nhuan but
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this bai viet nhuan but.
	 *
	 * @param userName the user name of this bai viet nhuan but
	 */
	public void setUserName(String userName);

	/**
	 * Returns the user ID of this bai viet nhuan but.
	 *
	 * @return the user ID of this bai viet nhuan but
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this bai viet nhuan but.
	 *
	 * @param userId the user ID of this bai viet nhuan but
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this bai viet nhuan but.
	 *
	 * @return the user uuid of this bai viet nhuan but
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this bai viet nhuan but.
	 *
	 * @param userUuid the user uuid of this bai viet nhuan but
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the type of this bai viet nhuan but.
	 *
	 * @return the type of this bai viet nhuan but
	 */
	public int getType();

	/**
	 * Sets the type of this bai viet nhuan but.
	 *
	 * @param type the type of this bai viet nhuan but
	 */
	public void setType(int type);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.viettel.portal.thongke.model.BaiVietNhuanBut baiVietNhuanBut);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.viettel.portal.thongke.model.BaiVietNhuanBut> toCacheModel();

	@Override
	public com.viettel.portal.thongke.model.BaiVietNhuanBut toEscapedModel();

	@Override
	public com.viettel.portal.thongke.model.BaiVietNhuanBut toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}