/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.thongke.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ContentProfit service. Represents a row in the &quot;vcms_Content_Profit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viettel.portal.thongke.model.impl.ContentProfitModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viettel.portal.thongke.model.impl.ContentProfitImpl}.
 * </p>
 *
 * @author lamvn
 * @see ContentProfit
 * @see com.viettel.portal.thongke.model.impl.ContentProfitImpl
 * @see com.viettel.portal.thongke.model.impl.ContentProfitModelImpl
 * @generated
 */
public interface ContentProfitModel extends BaseModel<ContentProfit>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a content profit model instance should use the {@link ContentProfit} interface instead.
	 */

	/**
	 * Returns the primary key of this content profit.
	 *
	 * @return the primary key of this content profit
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this content profit.
	 *
	 * @param primaryKey the primary key of this content profit
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the content ID of this content profit.
	 *
	 * @return the content ID of this content profit
	 */
	public long getContentId();

	/**
	 * Sets the content ID of this content profit.
	 *
	 * @param contentId the content ID of this content profit
	 */
	public void setContentId(long contentId);

	/**
	 * Returns the group ID of this content profit.
	 *
	 * @return the group ID of this content profit
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this content profit.
	 *
	 * @param groupId the group ID of this content profit
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this content profit.
	 *
	 * @return the company ID of this content profit
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this content profit.
	 *
	 * @param companyId the company ID of this content profit
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this content profit.
	 *
	 * @return the user ID of this content profit
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this content profit.
	 *
	 * @param userId the user ID of this content profit
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this content profit.
	 *
	 * @return the user uuid of this content profit
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this content profit.
	 *
	 * @param userUuid the user uuid of this content profit
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this content profit.
	 *
	 * @return the user name of this content profit
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this content profit.
	 *
	 * @param userName the user name of this content profit
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this content profit.
	 *
	 * @return the create date of this content profit
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this content profit.
	 *
	 * @param createDate the create date of this content profit
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this content profit.
	 *
	 * @return the modified date of this content profit
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this content profit.
	 *
	 * @param modifiedDate the modified date of this content profit
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the distributed date of this content profit.
	 *
	 * @return the distributed date of this content profit
	 */
	public Date getDistributedDate();

	/**
	 * Sets the distributed date of this content profit.
	 *
	 * @param distributedDate the distributed date of this content profit
	 */
	public void setDistributedDate(Date distributedDate);

	/**
	 * Returns the content type i d of this content profit.
	 *
	 * @return the content type i d of this content profit
	 */
	public int getContentTypeID();

	/**
	 * Sets the content type i d of this content profit.
	 *
	 * @param contentTypeID the content type i d of this content profit
	 */
	public void setContentTypeID(int contentTypeID);

	/**
	 * Returns the headline of this content profit.
	 *
	 * @return the headline of this content profit
	 */
	@AutoEscape
	public String getHeadline();

	/**
	 * Sets the headline of this content profit.
	 *
	 * @param headline the headline of this content profit
	 */
	public void setHeadline(String headline);

	/**
	 * Returns the cost of this content profit.
	 *
	 * @return the cost of this content profit
	 */
	public double getCost();

	/**
	 * Sets the cost of this content profit.
	 *
	 * @param cost the cost of this content profit
	 */
	public void setCost(double cost);

	/**
	 * Returns the status of this content profit.
	 *
	 * @return the status of this content profit
	 */
	public int getStatus();

	/**
	 * Sets the status of this content profit.
	 *
	 * @param status the status of this content profit
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.viettel.portal.thongke.model.ContentProfit contentProfit);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.viettel.portal.thongke.model.ContentProfit> toCacheModel();

	@Override
	public com.viettel.portal.thongke.model.ContentProfit toEscapedModel();

	@Override
	public com.viettel.portal.thongke.model.ContentProfit toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}