/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.thongke.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ContentType service. Represents a row in the &quot;vcms_Content_Type&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viettel.portal.thongke.model.impl.ContentTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viettel.portal.thongke.model.impl.ContentTypeImpl}.
 * </p>
 *
 * @author lamvn
 * @see ContentType
 * @see com.viettel.portal.thongke.model.impl.ContentTypeImpl
 * @see com.viettel.portal.thongke.model.impl.ContentTypeModelImpl
 * @generated
 */
public interface ContentTypeModel extends BaseModel<ContentType> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a content type model instance should use the {@link ContentType} interface instead.
	 */

	/**
	 * Returns the primary key of this content type.
	 *
	 * @return the primary key of this content type
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this content type.
	 *
	 * @param primaryKey the primary key of this content type
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the conten type ID of this content type.
	 *
	 * @return the conten type ID of this content type
	 */
	public int getContenTypeId();

	/**
	 * Sets the conten type ID of this content type.
	 *
	 * @param contenTypeId the conten type ID of this content type
	 */
	public void setContenTypeId(int contenTypeId);

	/**
	 * Returns the group ID of this content type.
	 *
	 * @return the group ID of this content type
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this content type.
	 *
	 * @param groupId the group ID of this content type
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this content type.
	 *
	 * @return the company ID of this content type
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this content type.
	 *
	 * @param companyId the company ID of this content type
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this content type.
	 *
	 * @return the user ID of this content type
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this content type.
	 *
	 * @param userId the user ID of this content type
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this content type.
	 *
	 * @return the user uuid of this content type
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this content type.
	 *
	 * @param userUuid the user uuid of this content type
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the name of this content type.
	 *
	 * @return the name of this content type
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this content type.
	 *
	 * @param name the name of this content type
	 */
	public void setName(String name);

	/**
	 * Returns the description of this content type.
	 *
	 * @return the description of this content type
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this content type.
	 *
	 * @param description the description of this content type
	 */
	public void setDescription(String description);

	/**
	 * Returns the sort order of this content type.
	 *
	 * @return the sort order of this content type
	 */
	public int getSortOrder();

	/**
	 * Sets the sort order of this content type.
	 *
	 * @param sortOrder the sort order of this content type
	 */
	public void setSortOrder(int sortOrder);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.viettel.portal.thongke.model.ContentType contentType);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.viettel.portal.thongke.model.ContentType> toCacheModel();

	@Override
	public com.viettel.portal.thongke.model.ContentType toEscapedModel();

	@Override
	public com.viettel.portal.thongke.model.ContentType toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}