/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.thongke.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PhongBanNhuanBut service. Represents a row in the &quot;portal_phongbannhuanbut&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viettel.portal.thongke.model.impl.PhongBanNhuanButModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viettel.portal.thongke.model.impl.PhongBanNhuanButImpl}.
 * </p>
 *
 * @author lamvn
 * @see PhongBanNhuanBut
 * @see com.viettel.portal.thongke.model.impl.PhongBanNhuanButImpl
 * @see com.viettel.portal.thongke.model.impl.PhongBanNhuanButModelImpl
 * @generated
 */
public interface PhongBanNhuanButModel extends BaseModel<PhongBanNhuanBut> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a phong ban nhuan but model instance should use the {@link PhongBanNhuanBut} interface instead.
	 */

	/**
	 * Returns the primary key of this phong ban nhuan but.
	 *
	 * @return the primary key of this phong ban nhuan but
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this phong ban nhuan but.
	 *
	 * @param primaryKey the primary key of this phong ban nhuan but
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this phong ban nhuan but.
	 *
	 * @return the ID of this phong ban nhuan but
	 */
	public long getId();

	/**
	 * Sets the ID of this phong ban nhuan but.
	 *
	 * @param id the ID of this phong ban nhuan but
	 */
	public void setId(long id);

	/**
	 * Returns the caption of this phong ban nhuan but.
	 *
	 * @return the caption of this phong ban nhuan but
	 */
	@AutoEscape
	public String getCaption();

	/**
	 * Sets the caption of this phong ban nhuan but.
	 *
	 * @param caption the caption of this phong ban nhuan but
	 */
	public void setCaption(String caption);

	/**
	 * Returns the from date of this phong ban nhuan but.
	 *
	 * @return the from date of this phong ban nhuan but
	 */
	public Date getFromDate();

	/**
	 * Sets the from date of this phong ban nhuan but.
	 *
	 * @param fromDate the from date of this phong ban nhuan but
	 */
	public void setFromDate(Date fromDate);

	/**
	 * Returns the to date of this phong ban nhuan but.
	 *
	 * @return the to date of this phong ban nhuan but
	 */
	public Date getToDate();

	/**
	 * Sets the to date of this phong ban nhuan but.
	 *
	 * @param toDate the to date of this phong ban nhuan but
	 */
	public void setToDate(Date toDate);

	/**
	 * Returns the status of this phong ban nhuan but.
	 *
	 * @return the status of this phong ban nhuan but
	 */
	public boolean getStatus();

	/**
	 * Returns <code>true</code> if this phong ban nhuan but is status.
	 *
	 * @return <code>true</code> if this phong ban nhuan but is status; <code>false</code> otherwise
	 */
	public boolean isStatus();

	/**
	 * Sets whether this phong ban nhuan but is status.
	 *
	 * @param status the status of this phong ban nhuan but
	 */
	public void setStatus(boolean status);

	/**
	 * Returns the company ID of this phong ban nhuan but.
	 *
	 * @return the company ID of this phong ban nhuan but
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this phong ban nhuan but.
	 *
	 * @param companyId the company ID of this phong ban nhuan but
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this phong ban nhuan but.
	 *
	 * @return the group ID of this phong ban nhuan but
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this phong ban nhuan but.
	 *
	 * @param groupId the group ID of this phong ban nhuan but
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this phong ban nhuan but.
	 *
	 * @return the create date of this phong ban nhuan but
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this phong ban nhuan but.
	 *
	 * @param createDate the create date of this phong ban nhuan but
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modify date of this phong ban nhuan but.
	 *
	 * @return the modify date of this phong ban nhuan but
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this phong ban nhuan but.
	 *
	 * @param modifyDate the modify date of this phong ban nhuan but
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the user name of this phong ban nhuan but.
	 *
	 * @return the user name of this phong ban nhuan but
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this phong ban nhuan but.
	 *
	 * @param userName the user name of this phong ban nhuan but
	 */
	public void setUserName(String userName);

	/**
	 * Returns the user ID of this phong ban nhuan but.
	 *
	 * @return the user ID of this phong ban nhuan but
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this phong ban nhuan but.
	 *
	 * @param userId the user ID of this phong ban nhuan but
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this phong ban nhuan but.
	 *
	 * @return the user uuid of this phong ban nhuan but
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this phong ban nhuan but.
	 *
	 * @param userUuid the user uuid of this phong ban nhuan but
	 */
	public void setUserUuid(String userUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.viettel.portal.thongke.model.PhongBanNhuanBut phongBanNhuanBut);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.viettel.portal.thongke.model.PhongBanNhuanBut> toCacheModel();

	@Override
	public com.viettel.portal.thongke.model.PhongBanNhuanBut toEscapedModel();

	@Override
	public com.viettel.portal.thongke.model.PhongBanNhuanBut toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}