/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.thongke.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PhongBanNhuanButChiTiet service. Represents a row in the &quot;portal_phongbannhuanbutchitiet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viettel.portal.thongke.model.impl.PhongBanNhuanButChiTietModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viettel.portal.thongke.model.impl.PhongBanNhuanButChiTietImpl}.
 * </p>
 *
 * @author lamvn
 * @see PhongBanNhuanButChiTiet
 * @see com.viettel.portal.thongke.model.impl.PhongBanNhuanButChiTietImpl
 * @see com.viettel.portal.thongke.model.impl.PhongBanNhuanButChiTietModelImpl
 * @generated
 */
public interface PhongBanNhuanButChiTietModel extends BaseModel<PhongBanNhuanButChiTiet> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a phong ban nhuan but chi tiet model instance should use the {@link PhongBanNhuanButChiTiet} interface instead.
	 */

	/**
	 * Returns the primary key of this phong ban nhuan but chi tiet.
	 *
	 * @return the primary key of this phong ban nhuan but chi tiet
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this phong ban nhuan but chi tiet.
	 *
	 * @param primaryKey the primary key of this phong ban nhuan but chi tiet
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this phong ban nhuan but chi tiet.
	 *
	 * @return the ID of this phong ban nhuan but chi tiet
	 */
	public long getId();

	/**
	 * Sets the ID of this phong ban nhuan but chi tiet.
	 *
	 * @param id the ID of this phong ban nhuan but chi tiet
	 */
	public void setId(long id);

	/**
	 * Returns the phong ban nhuan but ID of this phong ban nhuan but chi tiet.
	 *
	 * @return the phong ban nhuan but ID of this phong ban nhuan but chi tiet
	 */
	public long getPhongBanNhuanButId();

	/**
	 * Sets the phong ban nhuan but ID of this phong ban nhuan but chi tiet.
	 *
	 * @param phongBanNhuanButId the phong ban nhuan but ID of this phong ban nhuan but chi tiet
	 */
	public void setPhongBanNhuanButId(long phongBanNhuanButId);

	/**
	 * Returns the phong ban ID of this phong ban nhuan but chi tiet.
	 *
	 * @return the phong ban ID of this phong ban nhuan but chi tiet
	 */
	public long getPhongBanId();

	/**
	 * Sets the phong ban ID of this phong ban nhuan but chi tiet.
	 *
	 * @param phongBanId the phong ban ID of this phong ban nhuan but chi tiet
	 */
	public void setPhongBanId(long phongBanId);

	/**
	 * Returns the phong ban ten of this phong ban nhuan but chi tiet.
	 *
	 * @return the phong ban ten of this phong ban nhuan but chi tiet
	 */
	@AutoEscape
	public String getPhongBanTen();

	/**
	 * Sets the phong ban ten of this phong ban nhuan but chi tiet.
	 *
	 * @param phongBanTen the phong ban ten of this phong ban nhuan but chi tiet
	 */
	public void setPhongBanTen(String phongBanTen);

	/**
	 * Returns the rating of this phong ban nhuan but chi tiet.
	 *
	 * @return the rating of this phong ban nhuan but chi tiet
	 */
	@AutoEscape
	public String getRating();

	/**
	 * Sets the rating of this phong ban nhuan but chi tiet.
	 *
	 * @param rating the rating of this phong ban nhuan but chi tiet
	 */
	public void setRating(String rating);

	/**
	 * Returns the rating value of this phong ban nhuan but chi tiet.
	 *
	 * @return the rating value of this phong ban nhuan but chi tiet
	 */
	public double getRatingValue();

	/**
	 * Sets the rating value of this phong ban nhuan but chi tiet.
	 *
	 * @param ratingValue the rating value of this phong ban nhuan but chi tiet
	 */
	public void setRatingValue(double ratingValue);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.viettel.portal.thongke.model.PhongBanNhuanButChiTiet phongBanNhuanButChiTiet);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.viettel.portal.thongke.model.PhongBanNhuanButChiTiet> toCacheModel();

	@Override
	public com.viettel.portal.thongke.model.PhongBanNhuanButChiTiet toEscapedModel();

	@Override
	public com.viettel.portal.thongke.model.PhongBanNhuanButChiTiet toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}