/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.thongke.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PhongBan service. Represents a row in the &quot;portal_phongban&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viettel.portal.thongke.model.impl.PhongBanModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viettel.portal.thongke.model.impl.PhongBanImpl}.
 * </p>
 *
 * @author lamvn
 * @see PhongBan
 * @see com.viettel.portal.thongke.model.impl.PhongBanImpl
 * @see com.viettel.portal.thongke.model.impl.PhongBanModelImpl
 * @generated
 */
public interface PhongBanModel extends BaseModel<PhongBan> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a phong ban model instance should use the {@link PhongBan} interface instead.
	 */

	/**
	 * Returns the primary key of this phong ban.
	 *
	 * @return the primary key of this phong ban
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this phong ban.
	 *
	 * @param primaryKey the primary key of this phong ban
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this phong ban.
	 *
	 * @return the ID of this phong ban
	 */
	public long getId();

	/**
	 * Sets the ID of this phong ban.
	 *
	 * @param id the ID of this phong ban
	 */
	public void setId(long id);

	/**
	 * Returns the name of this phong ban.
	 *
	 * @return the name of this phong ban
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this phong ban.
	 *
	 * @param name the name of this phong ban
	 */
	public void setName(String name);

	/**
	 * Returns the order_ of this phong ban.
	 *
	 * @return the order_ of this phong ban
	 */
	public int getOrder_();

	/**
	 * Sets the order_ of this phong ban.
	 *
	 * @param order_ the order_ of this phong ban
	 */
	public void setOrder_(int order_);

	/**
	 * Returns the descriptions of this phong ban.
	 *
	 * @return the descriptions of this phong ban
	 */
	@AutoEscape
	public String getDescriptions();

	/**
	 * Sets the descriptions of this phong ban.
	 *
	 * @param descriptions the descriptions of this phong ban
	 */
	public void setDescriptions(String descriptions);

	/**
	 * Returns the status of this phong ban.
	 *
	 * @return the status of this phong ban
	 */
	public boolean getStatus();

	/**
	 * Returns <code>true</code> if this phong ban is status.
	 *
	 * @return <code>true</code> if this phong ban is status; <code>false</code> otherwise
	 */
	public boolean isStatus();

	/**
	 * Sets whether this phong ban is status.
	 *
	 * @param status the status of this phong ban
	 */
	public void setStatus(boolean status);

	/**
	 * Returns the company ID of this phong ban.
	 *
	 * @return the company ID of this phong ban
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this phong ban.
	 *
	 * @param companyId the company ID of this phong ban
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this phong ban.
	 *
	 * @return the group ID of this phong ban
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this phong ban.
	 *
	 * @param groupId the group ID of this phong ban
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this phong ban.
	 *
	 * @return the create date of this phong ban
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this phong ban.
	 *
	 * @param createDate the create date of this phong ban
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modify date of this phong ban.
	 *
	 * @return the modify date of this phong ban
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this phong ban.
	 *
	 * @param modifyDate the modify date of this phong ban
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the user name of this phong ban.
	 *
	 * @return the user name of this phong ban
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this phong ban.
	 *
	 * @param userName the user name of this phong ban
	 */
	public void setUserName(String userName);

	/**
	 * Returns the user ID of this phong ban.
	 *
	 * @return the user ID of this phong ban
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this phong ban.
	 *
	 * @param userId the user ID of this phong ban
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this phong ban.
	 *
	 * @return the user uuid of this phong ban
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this phong ban.
	 *
	 * @param userUuid the user uuid of this phong ban
	 */
	public void setUserUuid(String userUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.viettel.portal.thongke.model.PhongBan phongBan);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.viettel.portal.thongke.model.PhongBan> toCacheModel();

	@Override
	public com.viettel.portal.thongke.model.PhongBan toEscapedModel();

	@Override
	public com.viettel.portal.thongke.model.PhongBan toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}