/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.links.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VLink service. Represents a row in the &quot;portal_link&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viettel.portal.links.model.impl.VLinkModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viettel.portal.links.model.impl.VLinkImpl}.
 * </p>
 *
 * @author ChucHV
 * @see VLink
 * @see com.viettel.portal.links.model.impl.VLinkImpl
 * @see com.viettel.portal.links.model.impl.VLinkModelImpl
 * @generated
 */
public interface VLinkModel extends BaseModel<VLink>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a v link model instance should use the {@link VLink} interface instead.
	 */

	/**
	 * Returns the primary key of this v link.
	 *
	 * @return the primary key of this v link
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this v link.
	 *
	 * @param primaryKey the primary key of this v link
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the link ID of this v link.
	 *
	 * @return the link ID of this v link
	 */
	public long getLinkId();

	/**
	 * Sets the link ID of this v link.
	 *
	 * @param linkId the link ID of this v link
	 */
	public void setLinkId(long linkId);

	/**
	 * Returns the group ID of this v link.
	 *
	 * @return the group ID of this v link
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this v link.
	 *
	 * @param groupId the group ID of this v link
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this v link.
	 *
	 * @return the company ID of this v link
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this v link.
	 *
	 * @param companyId the company ID of this v link
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this v link.
	 *
	 * @return the user ID of this v link
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this v link.
	 *
	 * @param userId the user ID of this v link
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this v link.
	 *
	 * @return the user uuid of this v link
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this v link.
	 *
	 * @param userUuid the user uuid of this v link
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this v link.
	 *
	 * @return the user name of this v link
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this v link.
	 *
	 * @param userName the user name of this v link
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this v link.
	 *
	 * @return the create date of this v link
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this v link.
	 *
	 * @param createDate the create date of this v link
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this v link.
	 *
	 * @return the modified date of this v link
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this v link.
	 *
	 * @param modifiedDate the modified date of this v link
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the link name of this v link.
	 *
	 * @return the link name of this v link
	 */
	@AutoEscape
	public String getLinkName();

	/**
	 * Sets the link name of this v link.
	 *
	 * @param linkName the link name of this v link
	 */
	public void setLinkName(String linkName);

	/**
	 * Returns the url of this v link.
	 *
	 * @return the url of this v link
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this v link.
	 *
	 * @param url the url of this v link
	 */
	public void setUrl(String url);

	/**
	 * Returns the is active of this v link.
	 *
	 * @return the is active of this v link
	 */
	public boolean getIsActive();

	/**
	 * Returns <code>true</code> if this v link is is active.
	 *
	 * @return <code>true</code> if this v link is is active; <code>false</code> otherwise
	 */
	public boolean isIsActive();

	/**
	 * Sets whether this v link is is active.
	 *
	 * @param isActive the is active of this v link
	 */
	public void setIsActive(boolean isActive);

	/**
	 * Returns the corder of this v link.
	 *
	 * @return the corder of this v link
	 */
	public int getCorder();

	/**
	 * Sets the corder of this v link.
	 *
	 * @param corder the corder of this v link
	 */
	public void setCorder(int corder);

	/**
	 * Returns the category ID of this v link.
	 *
	 * @return the category ID of this v link
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this v link.
	 *
	 * @param categoryId the category ID of this v link
	 */
	public void setCategoryId(long categoryId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.viettel.portal.links.model.VLink vLink);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.viettel.portal.links.model.VLink> toCacheModel();

	@Override
	public com.viettel.portal.links.model.VLink toEscapedModel();

	@Override
	public com.viettel.portal.links.model.VLink toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}