/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.revotech.portal.tthc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LegalDocument service. Represents a row in the &quot;tthc_LegalDocument&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.revotech.portal.tthc.model.impl.LegalDocumentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.revotech.portal.tthc.model.impl.LegalDocumentImpl}.
 * </p>
 *
 * @author hieptran
 * @see LegalDocument
 * @see com.revotech.portal.tthc.model.impl.LegalDocumentImpl
 * @see com.revotech.portal.tthc.model.impl.LegalDocumentModelImpl
 * @generated
 */
public interface LegalDocumentModel extends BaseModel<LegalDocument>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a legal document model instance should use the {@link LegalDocument} interface instead.
	 */

	/**
	 * Returns the primary key of this legal document.
	 *
	 * @return the primary key of this legal document
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this legal document.
	 *
	 * @param primaryKey the primary key of this legal document
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ld ID of this legal document.
	 *
	 * @return the ld ID of this legal document
	 */
	public long getLdId();

	/**
	 * Sets the ld ID of this legal document.
	 *
	 * @param ldId the ld ID of this legal document
	 */
	public void setLdId(long ldId);

	/**
	 * Returns the group ID of this legal document.
	 *
	 * @return the group ID of this legal document
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this legal document.
	 *
	 * @param groupId the group ID of this legal document
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this legal document.
	 *
	 * @return the company ID of this legal document
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this legal document.
	 *
	 * @param companyId the company ID of this legal document
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this legal document.
	 *
	 * @return the user ID of this legal document
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this legal document.
	 *
	 * @param userId the user ID of this legal document
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this legal document.
	 *
	 * @return the user uuid of this legal document
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this legal document.
	 *
	 * @param userUuid the user uuid of this legal document
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this legal document.
	 *
	 * @return the user name of this legal document
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this legal document.
	 *
	 * @param userName the user name of this legal document
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this legal document.
	 *
	 * @return the create date of this legal document
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this legal document.
	 *
	 * @param createDate the create date of this legal document
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this legal document.
	 *
	 * @return the modified date of this legal document
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this legal document.
	 *
	 * @param modifiedDate the modified date of this legal document
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ld code of this legal document.
	 *
	 * @return the ld code of this legal document
	 */
	@AutoEscape
	public String getLdCode();

	/**
	 * Sets the ld code of this legal document.
	 *
	 * @param ldCode the ld code of this legal document
	 */
	public void setLdCode(String ldCode);

	/**
	 * Returns the ld title of this legal document.
	 *
	 * @return the ld title of this legal document
	 */
	@AutoEscape
	public String getLdTitle();

	/**
	 * Sets the ld title of this legal document.
	 *
	 * @param ldTitle the ld title of this legal document
	 */
	public void setLdTitle(String ldTitle);

	/**
	 * Returns the ld link of this legal document.
	 *
	 * @return the ld link of this legal document
	 */
	@AutoEscape
	public String getLdLink();

	/**
	 * Sets the ld link of this legal document.
	 *
	 * @param ldLink the ld link of this legal document
	 */
	public void setLdLink(String ldLink);

	/**
	 * Returns the ld level3 link of this legal document.
	 *
	 * @return the ld level3 link of this legal document
	 */
	@AutoEscape
	public String getLdLevel3Link();

	/**
	 * Sets the ld level3 link of this legal document.
	 *
	 * @param ldLevel3Link the ld level3 link of this legal document
	 */
	public void setLdLevel3Link(String ldLevel3Link);

	/**
	 * Returns the ld subcontent of this legal document.
	 *
	 * @return the ld subcontent of this legal document
	 */
	@AutoEscape
	public String getLdSubcontent();

	/**
	 * Sets the ld subcontent of this legal document.
	 *
	 * @param ldSubcontent the ld subcontent of this legal document
	 */
	public void setLdSubcontent(String ldSubcontent);

	/**
	 * Returns the is active of this legal document.
	 *
	 * @return the is active of this legal document
	 */
	public boolean getIsActive();

	/**
	 * Returns <code>true</code> if this legal document is is active.
	 *
	 * @return <code>true</code> if this legal document is is active; <code>false</code> otherwise
	 */
	public boolean isIsActive();

	/**
	 * Sets whether this legal document is is active.
	 *
	 * @param isActive the is active of this legal document
	 */
	public void setIsActive(boolean isActive);

	/**
	 * Returns the id linhvuc of this legal document.
	 *
	 * @return the id linhvuc of this legal document
	 */
	public long getIdLinhvuc();

	/**
	 * Sets the id linhvuc of this legal document.
	 *
	 * @param idLinhvuc the id linhvuc of this legal document
	 */
	public void setIdLinhvuc(long idLinhvuc);

	/**
	 * Returns the id coquanbanhanh of this legal document.
	 *
	 * @return the id coquanbanhanh of this legal document
	 */
	public long getIdCoquanbanhanh();

	/**
	 * Sets the id coquanbanhanh of this legal document.
	 *
	 * @param idCoquanbanhanh the id coquanbanhanh of this legal document
	 */
	public void setIdCoquanbanhanh(long idCoquanbanhanh);

	/**
	 * Returns the ld donvithuchien of this legal document.
	 *
	 * @return the ld donvithuchien of this legal document
	 */
	@AutoEscape
	public String getLdDonvithuchien();

	/**
	 * Sets the ld donvithuchien of this legal document.
	 *
	 * @param ldDonvithuchien the ld donvithuchien of this legal document
	 */
	public void setLdDonvithuchien(String ldDonvithuchien);

	/**
	 * Returns the ld level of this legal document.
	 *
	 * @return the ld level of this legal document
	 */
	public int getLdLevel();

	/**
	 * Sets the ld level of this legal document.
	 *
	 * @param ldLevel the ld level of this legal document
	 */
	public void setLdLevel(int ldLevel);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.revotech.portal.tthc.model.LegalDocument legalDocument);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.revotech.portal.tthc.model.LegalDocument> toCacheModel();

	@Override
	public com.revotech.portal.tthc.model.LegalDocument toEscapedModel();

	@Override
	public com.revotech.portal.tthc.model.LegalDocument toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}