/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.magazine.archive.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import com.viettel.portal.magazine.archive.model.Magazine;
import com.viettel.portal.magazine.archive.service.MagazineService;
import com.viettel.portal.magazine.archive.service.persistence.ContentPersistence;
import com.viettel.portal.magazine.archive.service.persistence.MagazinePersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the magazine remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.viettel.portal.magazine.archive.service.impl.MagazineServiceImpl}.
 * </p>
 *
 * @author namtv
 * @see com.viettel.portal.magazine.archive.service.impl.MagazineServiceImpl
 * @see com.viettel.portal.magazine.archive.service.MagazineServiceUtil
 * @generated
 */
public abstract class MagazineServiceBaseImpl extends BaseServiceImpl
	implements MagazineService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.viettel.portal.magazine.archive.service.MagazineServiceUtil} to access the magazine remote service.
	 */

	/**
	 * Returns the content local service.
	 *
	 * @return the content local service
	 */
	public com.viettel.portal.magazine.archive.service.ContentLocalService getContentLocalService() {
		return contentLocalService;
	}

	/**
	 * Sets the content local service.
	 *
	 * @param contentLocalService the content local service
	 */
	public void setContentLocalService(
		com.viettel.portal.magazine.archive.service.ContentLocalService contentLocalService) {
		this.contentLocalService = contentLocalService;
	}

	/**
	 * Returns the content remote service.
	 *
	 * @return the content remote service
	 */
	public com.viettel.portal.magazine.archive.service.ContentService getContentService() {
		return contentService;
	}

	/**
	 * Sets the content remote service.
	 *
	 * @param contentService the content remote service
	 */
	public void setContentService(
		com.viettel.portal.magazine.archive.service.ContentService contentService) {
		this.contentService = contentService;
	}

	/**
	 * Returns the content persistence.
	 *
	 * @return the content persistence
	 */
	public ContentPersistence getContentPersistence() {
		return contentPersistence;
	}

	/**
	 * Sets the content persistence.
	 *
	 * @param contentPersistence the content persistence
	 */
	public void setContentPersistence(ContentPersistence contentPersistence) {
		this.contentPersistence = contentPersistence;
	}

	/**
	 * Returns the magazine local service.
	 *
	 * @return the magazine local service
	 */
	public com.viettel.portal.magazine.archive.service.MagazineLocalService getMagazineLocalService() {
		return magazineLocalService;
	}

	/**
	 * Sets the magazine local service.
	 *
	 * @param magazineLocalService the magazine local service
	 */
	public void setMagazineLocalService(
		com.viettel.portal.magazine.archive.service.MagazineLocalService magazineLocalService) {
		this.magazineLocalService = magazineLocalService;
	}

	/**
	 * Returns the magazine remote service.
	 *
	 * @return the magazine remote service
	 */
	public com.viettel.portal.magazine.archive.service.MagazineService getMagazineService() {
		return magazineService;
	}

	/**
	 * Sets the magazine remote service.
	 *
	 * @param magazineService the magazine remote service
	 */
	public void setMagazineService(
		com.viettel.portal.magazine.archive.service.MagazineService magazineService) {
		this.magazineService = magazineService;
	}

	/**
	 * Returns the magazine persistence.
	 *
	 * @return the magazine persistence
	 */
	public MagazinePersistence getMagazinePersistence() {
		return magazinePersistence;
	}

	/**
	 * Sets the magazine persistence.
	 *
	 * @param magazinePersistence the magazine persistence
	 */
	public void setMagazinePersistence(MagazinePersistence magazinePersistence) {
		this.magazinePersistence = magazinePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return Magazine.class;
	}

	protected String getModelClassName() {
		return Magazine.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = magazinePersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.viettel.portal.magazine.archive.service.ContentLocalService.class)
	protected com.viettel.portal.magazine.archive.service.ContentLocalService contentLocalService;
	@BeanReference(type = com.viettel.portal.magazine.archive.service.ContentService.class)
	protected com.viettel.portal.magazine.archive.service.ContentService contentService;
	@BeanReference(type = ContentPersistence.class)
	protected ContentPersistence contentPersistence;
	@BeanReference(type = com.viettel.portal.magazine.archive.service.MagazineLocalService.class)
	protected com.viettel.portal.magazine.archive.service.MagazineLocalService magazineLocalService;
	@BeanReference(type = com.viettel.portal.magazine.archive.service.MagazineService.class)
	protected com.viettel.portal.magazine.archive.service.MagazineService magazineService;
	@BeanReference(type = MagazinePersistence.class)
	protected MagazinePersistence magazinePersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private MagazineServiceClpInvoker _clpInvoker = new MagazineServiceClpInvoker();
}