/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.videolibrary.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.viettel.portal.videolibrary.model.VLRelateVideo;
import com.viettel.portal.videolibrary.model.VLRelateVideoModel;
import com.viettel.portal.videolibrary.model.VLRelateVideoSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the VLRelateVideo service. Represents a row in the &quot;portal_relatevideo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.viettel.portal.videolibrary.model.VLRelateVideoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VLRelateVideoImpl}.
 * </p>
 *
 * @author ChucHV
 * @see VLRelateVideoImpl
 * @see com.viettel.portal.videolibrary.model.VLRelateVideo
 * @see com.viettel.portal.videolibrary.model.VLRelateVideoModel
 * @generated
 */
@JSON(strict = true)
public class VLRelateVideoModelImpl extends BaseModelImpl<VLRelateVideo>
	implements VLRelateVideoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a v l relate video model instance should use the {@link com.viettel.portal.videolibrary.model.VLRelateVideo} interface instead.
	 */
	public static final String TABLE_NAME = "portal_relatevideo";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "videoId", Types.BIGINT },
			{ "relateId", Types.BIGINT },
			{ "groupId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table portal_relatevideo (id_ LONG not null primary key,videoId LONG,relateId LONG,groupId LONG)";
	public static final String TABLE_SQL_DROP = "drop table portal_relatevideo";
	public static final String ORDER_BY_JPQL = " ORDER BY vlRelateVideo.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY portal_relatevideo.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.viettel.portal.videolibrary.model.VLRelateVideo"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.viettel.portal.videolibrary.model.VLRelateVideo"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.viettel.portal.videolibrary.model.VLRelateVideo"),
			true);
	public static long GROUPID_COLUMN_BITMASK = 1L;
	public static long RELATEID_COLUMN_BITMASK = 2L;
	public static long VIDEOID_COLUMN_BITMASK = 4L;
	public static long ID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static VLRelateVideo toModel(VLRelateVideoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		VLRelateVideo model = new VLRelateVideoImpl();

		model.setId(soapModel.getId());
		model.setVideoId(soapModel.getVideoId());
		model.setRelateId(soapModel.getRelateId());
		model.setGroupId(soapModel.getGroupId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<VLRelateVideo> toModels(VLRelateVideoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<VLRelateVideo> models = new ArrayList<VLRelateVideo>(soapModels.length);

		for (VLRelateVideoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.viettel.portal.videolibrary.model.VLRelateVideo"));

	public VLRelateVideoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return VLRelateVideo.class;
	}

	@Override
	public String getModelClassName() {
		return VLRelateVideo.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("videoId", getVideoId());
		attributes.put("relateId", getRelateId());
		attributes.put("groupId", getGroupId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long videoId = (Long)attributes.get("videoId");

		if (videoId != null) {
			setVideoId(videoId);
		}

		Long relateId = (Long)attributes.get("relateId");

		if (relateId != null) {
			setRelateId(relateId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public long getVideoId() {
		return _videoId;
	}

	@Override
	public void setVideoId(long videoId) {
		_columnBitmask |= VIDEOID_COLUMN_BITMASK;

		if (!_setOriginalVideoId) {
			_setOriginalVideoId = true;

			_originalVideoId = _videoId;
		}

		_videoId = videoId;
	}

	public long getOriginalVideoId() {
		return _originalVideoId;
	}

	@JSON
	@Override
	public long getRelateId() {
		return _relateId;
	}

	@Override
	public void setRelateId(long relateId) {
		_columnBitmask |= RELATEID_COLUMN_BITMASK;

		if (!_setOriginalRelateId) {
			_setOriginalRelateId = true;

			_originalRelateId = _relateId;
		}

		_relateId = relateId;
	}

	public long getOriginalRelateId() {
		return _originalRelateId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			VLRelateVideo.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public VLRelateVideo toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VLRelateVideo)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VLRelateVideoImpl vlRelateVideoImpl = new VLRelateVideoImpl();

		vlRelateVideoImpl.setId(getId());
		vlRelateVideoImpl.setVideoId(getVideoId());
		vlRelateVideoImpl.setRelateId(getRelateId());
		vlRelateVideoImpl.setGroupId(getGroupId());

		vlRelateVideoImpl.resetOriginalValues();

		return vlRelateVideoImpl;
	}

	@Override
	public int compareTo(VLRelateVideo vlRelateVideo) {
		long primaryKey = vlRelateVideo.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VLRelateVideo)) {
			return false;
		}

		VLRelateVideo vlRelateVideo = (VLRelateVideo)obj;

		long primaryKey = vlRelateVideo.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		VLRelateVideoModelImpl vlRelateVideoModelImpl = this;

		vlRelateVideoModelImpl._originalVideoId = vlRelateVideoModelImpl._videoId;

		vlRelateVideoModelImpl._setOriginalVideoId = false;

		vlRelateVideoModelImpl._originalRelateId = vlRelateVideoModelImpl._relateId;

		vlRelateVideoModelImpl._setOriginalRelateId = false;

		vlRelateVideoModelImpl._originalGroupId = vlRelateVideoModelImpl._groupId;

		vlRelateVideoModelImpl._setOriginalGroupId = false;

		vlRelateVideoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<VLRelateVideo> toCacheModel() {
		VLRelateVideoCacheModel vlRelateVideoCacheModel = new VLRelateVideoCacheModel();

		vlRelateVideoCacheModel.id = getId();

		vlRelateVideoCacheModel.videoId = getVideoId();

		vlRelateVideoCacheModel.relateId = getRelateId();

		vlRelateVideoCacheModel.groupId = getGroupId();

		return vlRelateVideoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", videoId=");
		sb.append(getVideoId());
		sb.append(", relateId=");
		sb.append(getRelateId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.viettel.portal.videolibrary.model.VLRelateVideo");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>videoId</column-name><column-value><![CDATA[");
		sb.append(getVideoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>relateId</column-name><column-value><![CDATA[");
		sb.append(getRelateId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = VLRelateVideo.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			VLRelateVideo.class
		};
	private long _id;
	private long _videoId;
	private long _originalVideoId;
	private boolean _setOriginalVideoId;
	private long _relateId;
	private long _originalRelateId;
	private boolean _setOriginalRelateId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _columnBitmask;
	private VLRelateVideo _escapedModel;
}