/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.videolibrary.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.viettel.portal.videolibrary.model.VLVideoCategory;
import com.viettel.portal.videolibrary.model.VLVideoCategoryModel;
import com.viettel.portal.videolibrary.model.VLVideoCategorySoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the VLVideoCategory service. Represents a row in the &quot;portal_videocategorymap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.viettel.portal.videolibrary.model.VLVideoCategoryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VLVideoCategoryImpl}.
 * </p>
 *
 * @author ChucHV
 * @see VLVideoCategoryImpl
 * @see com.viettel.portal.videolibrary.model.VLVideoCategory
 * @see com.viettel.portal.videolibrary.model.VLVideoCategoryModel
 * @generated
 */
@JSON(strict = true)
public class VLVideoCategoryModelImpl extends BaseModelImpl<VLVideoCategory>
	implements VLVideoCategoryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a v l video category model instance should use the {@link com.viettel.portal.videolibrary.model.VLVideoCategory} interface instead.
	 */
	public static final String TABLE_NAME = "portal_videocategorymap";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "categoryId", Types.BIGINT },
			{ "videoId", Types.BIGINT },
			{ "groupId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table portal_videocategorymap (id_ LONG not null primary key,categoryId LONG,videoId LONG,groupId LONG)";
	public static final String TABLE_SQL_DROP = "drop table portal_videocategorymap";
	public static final String ORDER_BY_JPQL = " ORDER BY vlVideoCategory.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY portal_videocategorymap.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.viettel.portal.videolibrary.model.VLVideoCategory"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.viettel.portal.videolibrary.model.VLVideoCategory"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.viettel.portal.videolibrary.model.VLVideoCategory"),
			true);
	public static long CATEGORYID_COLUMN_BITMASK = 1L;
	public static long GROUPID_COLUMN_BITMASK = 2L;
	public static long VIDEOID_COLUMN_BITMASK = 4L;
	public static long ID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static VLVideoCategory toModel(VLVideoCategorySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		VLVideoCategory model = new VLVideoCategoryImpl();

		model.setId(soapModel.getId());
		model.setCategoryId(soapModel.getCategoryId());
		model.setVideoId(soapModel.getVideoId());
		model.setGroupId(soapModel.getGroupId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<VLVideoCategory> toModels(
		VLVideoCategorySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<VLVideoCategory> models = new ArrayList<VLVideoCategory>(soapModels.length);

		for (VLVideoCategorySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.viettel.portal.videolibrary.model.VLVideoCategory"));

	public VLVideoCategoryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return VLVideoCategory.class;
	}

	@Override
	public String getModelClassName() {
		return VLVideoCategory.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("categoryId", getCategoryId());
		attributes.put("videoId", getVideoId());
		attributes.put("groupId", getGroupId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long categoryId = (Long)attributes.get("categoryId");

		if (categoryId != null) {
			setCategoryId(categoryId);
		}

		Long videoId = (Long)attributes.get("videoId");

		if (videoId != null) {
			setVideoId(videoId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public long getCategoryId() {
		return _categoryId;
	}

	@Override
	public void setCategoryId(long categoryId) {
		_columnBitmask |= CATEGORYID_COLUMN_BITMASK;

		if (!_setOriginalCategoryId) {
			_setOriginalCategoryId = true;

			_originalCategoryId = _categoryId;
		}

		_categoryId = categoryId;
	}

	public long getOriginalCategoryId() {
		return _originalCategoryId;
	}

	@JSON
	@Override
	public long getVideoId() {
		return _videoId;
	}

	@Override
	public void setVideoId(long videoId) {
		_columnBitmask |= VIDEOID_COLUMN_BITMASK;

		if (!_setOriginalVideoId) {
			_setOriginalVideoId = true;

			_originalVideoId = _videoId;
		}

		_videoId = videoId;
	}

	public long getOriginalVideoId() {
		return _originalVideoId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			VLVideoCategory.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public VLVideoCategory toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VLVideoCategory)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VLVideoCategoryImpl vlVideoCategoryImpl = new VLVideoCategoryImpl();

		vlVideoCategoryImpl.setId(getId());
		vlVideoCategoryImpl.setCategoryId(getCategoryId());
		vlVideoCategoryImpl.setVideoId(getVideoId());
		vlVideoCategoryImpl.setGroupId(getGroupId());

		vlVideoCategoryImpl.resetOriginalValues();

		return vlVideoCategoryImpl;
	}

	@Override
	public int compareTo(VLVideoCategory vlVideoCategory) {
		long primaryKey = vlVideoCategory.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VLVideoCategory)) {
			return false;
		}

		VLVideoCategory vlVideoCategory = (VLVideoCategory)obj;

		long primaryKey = vlVideoCategory.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		VLVideoCategoryModelImpl vlVideoCategoryModelImpl = this;

		vlVideoCategoryModelImpl._originalCategoryId = vlVideoCategoryModelImpl._categoryId;

		vlVideoCategoryModelImpl._setOriginalCategoryId = false;

		vlVideoCategoryModelImpl._originalVideoId = vlVideoCategoryModelImpl._videoId;

		vlVideoCategoryModelImpl._setOriginalVideoId = false;

		vlVideoCategoryModelImpl._originalGroupId = vlVideoCategoryModelImpl._groupId;

		vlVideoCategoryModelImpl._setOriginalGroupId = false;

		vlVideoCategoryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<VLVideoCategory> toCacheModel() {
		VLVideoCategoryCacheModel vlVideoCategoryCacheModel = new VLVideoCategoryCacheModel();

		vlVideoCategoryCacheModel.id = getId();

		vlVideoCategoryCacheModel.categoryId = getCategoryId();

		vlVideoCategoryCacheModel.videoId = getVideoId();

		vlVideoCategoryCacheModel.groupId = getGroupId();

		return vlVideoCategoryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", categoryId=");
		sb.append(getCategoryId());
		sb.append(", videoId=");
		sb.append(getVideoId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.viettel.portal.videolibrary.model.VLVideoCategory");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>categoryId</column-name><column-value><![CDATA[");
		sb.append(getCategoryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>videoId</column-name><column-value><![CDATA[");
		sb.append(getVideoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = VLVideoCategory.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			VLVideoCategory.class
		};
	private long _id;
	private long _categoryId;
	private long _originalCategoryId;
	private boolean _setOriginalCategoryId;
	private long _videoId;
	private long _originalVideoId;
	private boolean _setOriginalVideoId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _columnBitmask;
	private VLVideoCategory _escapedModel;
}