/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.liferay.viettel.portal.visitcounter.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import com.liferay.viettel.portal.visitcounter.model.VisitCounter;
import com.liferay.viettel.portal.visitcounter.service.VisitCounterService;
import com.liferay.viettel.portal.visitcounter.service.persistence.VisitCounterLogPersistence;
import com.liferay.viettel.portal.visitcounter.service.persistence.VisitCounterPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the visit counter remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.viettel.portal.visitcounter.service.impl.VisitCounterServiceImpl}.
 * </p>
 *
 * @author hiepth6
 * @see com.liferay.viettel.portal.visitcounter.service.impl.VisitCounterServiceImpl
 * @see com.liferay.viettel.portal.visitcounter.service.VisitCounterServiceUtil
 * @generated
 */
public abstract class VisitCounterServiceBaseImpl extends BaseServiceImpl
	implements VisitCounterService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.viettel.portal.visitcounter.service.VisitCounterServiceUtil} to access the visit counter remote service.
	 */

	/**
	 * Returns the visit counter local service.
	 *
	 * @return the visit counter local service
	 */
	public com.liferay.viettel.portal.visitcounter.service.VisitCounterLocalService getVisitCounterLocalService() {
		return visitCounterLocalService;
	}

	/**
	 * Sets the visit counter local service.
	 *
	 * @param visitCounterLocalService the visit counter local service
	 */
	public void setVisitCounterLocalService(
		com.liferay.viettel.portal.visitcounter.service.VisitCounterLocalService visitCounterLocalService) {
		this.visitCounterLocalService = visitCounterLocalService;
	}

	/**
	 * Returns the visit counter remote service.
	 *
	 * @return the visit counter remote service
	 */
	public com.liferay.viettel.portal.visitcounter.service.VisitCounterService getVisitCounterService() {
		return visitCounterService;
	}

	/**
	 * Sets the visit counter remote service.
	 *
	 * @param visitCounterService the visit counter remote service
	 */
	public void setVisitCounterService(
		com.liferay.viettel.portal.visitcounter.service.VisitCounterService visitCounterService) {
		this.visitCounterService = visitCounterService;
	}

	/**
	 * Returns the visit counter persistence.
	 *
	 * @return the visit counter persistence
	 */
	public VisitCounterPersistence getVisitCounterPersistence() {
		return visitCounterPersistence;
	}

	/**
	 * Sets the visit counter persistence.
	 *
	 * @param visitCounterPersistence the visit counter persistence
	 */
	public void setVisitCounterPersistence(
		VisitCounterPersistence visitCounterPersistence) {
		this.visitCounterPersistence = visitCounterPersistence;
	}

	/**
	 * Returns the visit counter log local service.
	 *
	 * @return the visit counter log local service
	 */
	public com.liferay.viettel.portal.visitcounter.service.VisitCounterLogLocalService getVisitCounterLogLocalService() {
		return visitCounterLogLocalService;
	}

	/**
	 * Sets the visit counter log local service.
	 *
	 * @param visitCounterLogLocalService the visit counter log local service
	 */
	public void setVisitCounterLogLocalService(
		com.liferay.viettel.portal.visitcounter.service.VisitCounterLogLocalService visitCounterLogLocalService) {
		this.visitCounterLogLocalService = visitCounterLogLocalService;
	}

	/**
	 * Returns the visit counter log remote service.
	 *
	 * @return the visit counter log remote service
	 */
	public com.liferay.viettel.portal.visitcounter.service.VisitCounterLogService getVisitCounterLogService() {
		return visitCounterLogService;
	}

	/**
	 * Sets the visit counter log remote service.
	 *
	 * @param visitCounterLogService the visit counter log remote service
	 */
	public void setVisitCounterLogService(
		com.liferay.viettel.portal.visitcounter.service.VisitCounterLogService visitCounterLogService) {
		this.visitCounterLogService = visitCounterLogService;
	}

	/**
	 * Returns the visit counter log persistence.
	 *
	 * @return the visit counter log persistence
	 */
	public VisitCounterLogPersistence getVisitCounterLogPersistence() {
		return visitCounterLogPersistence;
	}

	/**
	 * Sets the visit counter log persistence.
	 *
	 * @param visitCounterLogPersistence the visit counter log persistence
	 */
	public void setVisitCounterLogPersistence(
		VisitCounterLogPersistence visitCounterLogPersistence) {
		this.visitCounterLogPersistence = visitCounterLogPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return VisitCounter.class;
	}

	protected String getModelClassName() {
		return VisitCounter.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = visitCounterPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.liferay.viettel.portal.visitcounter.service.VisitCounterLocalService.class)
	protected com.liferay.viettel.portal.visitcounter.service.VisitCounterLocalService visitCounterLocalService;
	@BeanReference(type = com.liferay.viettel.portal.visitcounter.service.VisitCounterService.class)
	protected com.liferay.viettel.portal.visitcounter.service.VisitCounterService visitCounterService;
	@BeanReference(type = VisitCounterPersistence.class)
	protected VisitCounterPersistence visitCounterPersistence;
	@BeanReference(type = com.liferay.viettel.portal.visitcounter.service.VisitCounterLogLocalService.class)
	protected com.liferay.viettel.portal.visitcounter.service.VisitCounterLogLocalService visitCounterLogLocalService;
	@BeanReference(type = com.liferay.viettel.portal.visitcounter.service.VisitCounterLogService.class)
	protected com.liferay.viettel.portal.visitcounter.service.VisitCounterLogService visitCounterLogService;
	@BeanReference(type = VisitCounterLogPersistence.class)
	protected VisitCounterLogPersistence visitCounterLogPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private VisitCounterServiceClpInvoker _clpInvoker = new VisitCounterServiceClpInvoker();
}