/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.revotech.portal.videolibrary.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VideoClip service. Represents a row in the &quot;VideoClip&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.revotech.portal.videolibrary.model.impl.VideoClipModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.revotech.portal.videolibrary.model.impl.VideoClipImpl}.
 * </p>
 *
 * @author ChucHV
 * @see VideoClip
 * @see com.revotech.portal.videolibrary.model.impl.VideoClipImpl
 * @see com.revotech.portal.videolibrary.model.impl.VideoClipModelImpl
 * @generated
 */
public interface VideoClipModel extends BaseModel<VideoClip> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a video clip model instance should use the {@link VideoClip} interface instead.
	 */

	/**
	 * Returns the primary key of this video clip.
	 *
	 * @return the primary key of this video clip
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this video clip.
	 *
	 * @param primaryKey the primary key of this video clip
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the i d of this video clip.
	 *
	 * @return the i d of this video clip
	 */
	public int getID();

	/**
	 * Sets the i d of this video clip.
	 *
	 * @param ID the i d of this video clip
	 */
	public void setID(int ID);

	/**
	 * Returns the name of this video clip.
	 *
	 * @return the name of this video clip
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this video clip.
	 *
	 * @param Name the name of this video clip
	 */
	public void setName(String Name);

	/**
	 * Returns the category i d of this video clip.
	 *
	 * @return the category i d of this video clip
	 */
	public int getCategoryID();

	/**
	 * Sets the category i d of this video clip.
	 *
	 * @param CategoryID the category i d of this video clip
	 */
	public void setCategoryID(int CategoryID);

	/**
	 * Returns the description of this video clip.
	 *
	 * @return the description of this video clip
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this video clip.
	 *
	 * @param Description the description of this video clip
	 */
	public void setDescription(String Description);

	/**
	 * Returns the image url of this video clip.
	 *
	 * @return the image url of this video clip
	 */
	@AutoEscape
	public String getImageUrl();

	/**
	 * Sets the image url of this video clip.
	 *
	 * @param ImageUrl the image url of this video clip
	 */
	public void setImageUrl(String ImageUrl);

	/**
	 * Returns the video url of this video clip.
	 *
	 * @return the video url of this video clip
	 */
	@AutoEscape
	public String getVideoUrl();

	/**
	 * Sets the video url of this video clip.
	 *
	 * @param VideoUrl the video url of this video clip
	 */
	public void setVideoUrl(String VideoUrl);

	/**
	 * Returns the duration of this video clip.
	 *
	 * @return the duration of this video clip
	 */
	public int getDuration();

	/**
	 * Sets the duration of this video clip.
	 *
	 * @param Duration the duration of this video clip
	 */
	public void setDuration(int Duration);

	/**
	 * Returns the view count of this video clip.
	 *
	 * @return the view count of this video clip
	 */
	public int getViewCount();

	/**
	 * Sets the view count of this video clip.
	 *
	 * @param ViewCount the view count of this video clip
	 */
	public void setViewCount(int ViewCount);

	/**
	 * Returns the status of this video clip.
	 *
	 * @return the status of this video clip
	 */
	public int getStatus();

	/**
	 * Sets the status of this video clip.
	 *
	 * @param Status the status of this video clip
	 */
	public void setStatus(int Status);

	/**
	 * Returns the creation date of this video clip.
	 *
	 * @return the creation date of this video clip
	 */
	public Date getCreationDate();

	/**
	 * Sets the creation date of this video clip.
	 *
	 * @param CreationDate the creation date of this video clip
	 */
	public void setCreationDate(Date CreationDate);

	/**
	 * Returns the modified date of this video clip.
	 *
	 * @return the modified date of this video clip
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this video clip.
	 *
	 * @param ModifiedDate the modified date of this video clip
	 */
	public void setModifiedDate(Date ModifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.revotech.portal.videolibrary.model.VideoClip videoClip);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.revotech.portal.videolibrary.model.VideoClip> toCacheModel();

	@Override
	public com.revotech.portal.videolibrary.model.VideoClip toEscapedModel();

	@Override
	public com.revotech.portal.videolibrary.model.VideoClip toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}