/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.revotech.portal.videolibrary.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the VideoCategory service. Represents a row in the &quot;VideoCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.revotech.portal.videolibrary.model.impl.VideoCategoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.revotech.portal.videolibrary.model.impl.VideoCategoryImpl}.
 * </p>
 *
 * @author ChucHV
 * @see VideoCategory
 * @see com.revotech.portal.videolibrary.model.impl.VideoCategoryImpl
 * @see com.revotech.portal.videolibrary.model.impl.VideoCategoryModelImpl
 * @generated
 */
public interface VideoCategoryModel extends BaseModel<VideoCategory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a video category model instance should use the {@link VideoCategory} interface instead.
	 */

	/**
	 * Returns the primary key of this video category.
	 *
	 * @return the primary key of this video category
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this video category.
	 *
	 * @param primaryKey the primary key of this video category
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the i d of this video category.
	 *
	 * @return the i d of this video category
	 */
	public int getID();

	/**
	 * Sets the i d of this video category.
	 *
	 * @param ID the i d of this video category
	 */
	public void setID(int ID);

	/**
	 * Returns the name of this video category.
	 *
	 * @return the name of this video category
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this video category.
	 *
	 * @param Name the name of this video category
	 */
	public void setName(String Name);

	/**
	 * Returns the url of this video category.
	 *
	 * @return the url of this video category
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this video category.
	 *
	 * @param Url the url of this video category
	 */
	public void setUrl(String Url);

	/**
	 * Returns the sort order of this video category.
	 *
	 * @return the sort order of this video category
	 */
	public int getSortOrder();

	/**
	 * Sets the sort order of this video category.
	 *
	 * @param SortOrder the sort order of this video category
	 */
	public void setSortOrder(int SortOrder);

	/**
	 * Returns the item count of this video category.
	 *
	 * @return the item count of this video category
	 */
	public int getItemCount();

	/**
	 * Sets the item count of this video category.
	 *
	 * @param ItemCount the item count of this video category
	 */
	public void setItemCount(int ItemCount);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.revotech.portal.videolibrary.model.VideoCategory videoCategory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.revotech.portal.videolibrary.model.VideoCategory> toCacheModel();

	@Override
	public com.revotech.portal.videolibrary.model.VideoCategory toEscapedModel();

	@Override
	public com.revotech.portal.videolibrary.model.VideoCategory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}