/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.revotech.portal.videolibrary.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VLVideo service. Represents a row in the &quot;portal_video&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.revotech.portal.videolibrary.model.impl.VLVideoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.revotech.portal.videolibrary.model.impl.VLVideoImpl}.
 * </p>
 *
 * @author ChucHV
 * @see VLVideo
 * @see com.revotech.portal.videolibrary.model.impl.VLVideoImpl
 * @see com.revotech.portal.videolibrary.model.impl.VLVideoModelImpl
 * @generated
 */
public interface VLVideoModel extends BaseModel<VLVideo>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a v l video model instance should use the {@link VLVideo} interface instead.
	 */

	/**
	 * Returns the primary key of this v l video.
	 *
	 * @return the primary key of this v l video
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this v l video.
	 *
	 * @param primaryKey the primary key of this v l video
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the video ID of this v l video.
	 *
	 * @return the video ID of this v l video
	 */
	public long getVideoId();

	/**
	 * Sets the video ID of this v l video.
	 *
	 * @param videoId the video ID of this v l video
	 */
	public void setVideoId(long videoId);

	/**
	 * Returns the group ID of this v l video.
	 *
	 * @return the group ID of this v l video
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this v l video.
	 *
	 * @param groupId the group ID of this v l video
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this v l video.
	 *
	 * @return the company ID of this v l video
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this v l video.
	 *
	 * @param companyId the company ID of this v l video
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this v l video.
	 *
	 * @return the user ID of this v l video
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this v l video.
	 *
	 * @param userId the user ID of this v l video
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this v l video.
	 *
	 * @return the user uuid of this v l video
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this v l video.
	 *
	 * @param userUuid the user uuid of this v l video
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this v l video.
	 *
	 * @return the user name of this v l video
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this v l video.
	 *
	 * @param userName the user name of this v l video
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this v l video.
	 *
	 * @return the create date of this v l video
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this v l video.
	 *
	 * @param createDate the create date of this v l video
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this v l video.
	 *
	 * @return the modified date of this v l video
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this v l video.
	 *
	 * @param modifiedDate the modified date of this v l video
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the video name of this v l video.
	 *
	 * @return the video name of this v l video
	 */
	@AutoEscape
	public String getVideoName();

	/**
	 * Sets the video name of this v l video.
	 *
	 * @param videoName the video name of this v l video
	 */
	public void setVideoName(String videoName);

	/**
	 * Returns the description of this v l video.
	 *
	 * @return the description of this v l video
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this v l video.
	 *
	 * @param description the description of this v l video
	 */
	public void setDescription(String description);

	/**
	 * Returns the video type of this v l video.
	 *
	 * @return the video type of this v l video
	 */
	@AutoEscape
	public String getVideoType();

	/**
	 * Sets the video type of this v l video.
	 *
	 * @param videoType the video type of this v l video
	 */
	public void setVideoType(String videoType);

	/**
	 * Returns the video url of this v l video.
	 *
	 * @return the video url of this v l video
	 */
	@AutoEscape
	public String getVideoUrl();

	/**
	 * Sets the video url of this v l video.
	 *
	 * @param videoUrl the video url of this v l video
	 */
	public void setVideoUrl(String videoUrl);

	/**
	 * Returns the view count of this v l video.
	 *
	 * @return the view count of this v l video
	 */
	public int getViewCount();

	/**
	 * Sets the view count of this v l video.
	 *
	 * @param viewCount the view count of this v l video
	 */
	public void setViewCount(int viewCount);

	/**
	 * Returns the file ID of this v l video.
	 *
	 * @return the file ID of this v l video
	 */
	public long getFileId();

	/**
	 * Sets the file ID of this v l video.
	 *
	 * @param fileId the file ID of this v l video
	 */
	public void setFileId(long fileId);

	/**
	 * Returns the image of this v l video.
	 *
	 * @return the image of this v l video
	 */
	public boolean getImage();

	/**
	 * Returns <code>true</code> if this v l video is image.
	 *
	 * @return <code>true</code> if this v l video is image; <code>false</code> otherwise
	 */
	public boolean isImage();

	/**
	 * Sets whether this v l video is image.
	 *
	 * @param image the image of this v l video
	 */
	public void setImage(boolean image);

	/**
	 * Returns the image ID of this v l video.
	 *
	 * @return the image ID of this v l video
	 */
	public long getImageId();

	/**
	 * Sets the image ID of this v l video.
	 *
	 * @param imageId the image ID of this v l video
	 */
	public void setImageId(long imageId);

	/**
	 * Returns the small image url of this v l video.
	 *
	 * @return the small image url of this v l video
	 */
	@AutoEscape
	public String getSmallImageUrl();

	/**
	 * Sets the small image url of this v l video.
	 *
	 * @param smallImageUrl the small image url of this v l video
	 */
	public void setSmallImageUrl(String smallImageUrl);

	/**
	 * Returns the relate ID of this v l video.
	 *
	 * @return the relate ID of this v l video
	 */
	public long getRelateId();

	/**
	 * Sets the relate ID of this v l video.
	 *
	 * @param relateId the relate ID of this v l video
	 */
	public void setRelateId(long relateId);

	/**
	 * Returns the invisible of this v l video.
	 *
	 * @return the invisible of this v l video
	 */
	public boolean getInvisible();

	/**
	 * Returns <code>true</code> if this v l video is invisible.
	 *
	 * @return <code>true</code> if this v l video is invisible; <code>false</code> otherwise
	 */
	public boolean isInvisible();

	/**
	 * Sets whether this v l video is invisible.
	 *
	 * @param invisible the invisible of this v l video
	 */
	public void setInvisible(boolean invisible);

	/**
	 * Returns the category ID of this v l video.
	 *
	 * @return the category ID of this v l video
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this v l video.
	 *
	 * @param categoryId the category ID of this v l video
	 */
	public void setCategoryId(long categoryId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.revotech.portal.videolibrary.model.VLVideo vlVideo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.revotech.portal.videolibrary.model.VLVideo> toCacheModel();

	@Override
	public com.revotech.portal.videolibrary.model.VLVideo toEscapedModel();

	@Override
	public com.revotech.portal.videolibrary.model.VLVideo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}