/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.magazine.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MagazineContent service. Represents a row in the &quot;MagazineContent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viettel.portal.magazine.model.impl.MagazineContentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viettel.portal.magazine.model.impl.MagazineContentImpl}.
 * </p>
 *
 * @author namtv
 * @see MagazineContent
 * @see com.viettel.portal.magazine.model.impl.MagazineContentImpl
 * @see com.viettel.portal.magazine.model.impl.MagazineContentModelImpl
 * @generated
 */
public interface MagazineContentModel extends BaseModel<MagazineContent> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a magazine content model instance should use the {@link MagazineContent} interface instead.
	 */

	/**
	 * Returns the primary key of this magazine content.
	 *
	 * @return the primary key of this magazine content
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this magazine content.
	 *
	 * @param primaryKey the primary key of this magazine content
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the i d of this magazine content.
	 *
	 * @return the i d of this magazine content
	 */
	public int getID();

	/**
	 * Sets the i d of this magazine content.
	 *
	 * @param ID the i d of this magazine content
	 */
	public void setID(int ID);

	/**
	 * Returns the headline of this magazine content.
	 *
	 * @return the headline of this magazine content
	 */
	@AutoEscape
	public String getHeadline();

	/**
	 * Sets the headline of this magazine content.
	 *
	 * @param Headline the headline of this magazine content
	 */
	public void setHeadline(String Headline);

	/**
	 * Returns the teaser of this magazine content.
	 *
	 * @return the teaser of this magazine content
	 */
	@AutoEscape
	public String getTeaser();

	/**
	 * Sets the teaser of this magazine content.
	 *
	 * @param Teaser the teaser of this magazine content
	 */
	public void setTeaser(String Teaser);

	/**
	 * Returns the body of this magazine content.
	 *
	 * @return the body of this magazine content
	 */
	@AutoEscape
	public String getBody();

	/**
	 * Sets the body of this magazine content.
	 *
	 * @param Body the body of this magazine content
	 */
	public void setBody(String Body);

	/**
	 * Returns the magazine zone i d of this magazine content.
	 *
	 * @return the magazine zone i d of this magazine content
	 */
	public int getMagazineZoneID();

	/**
	 * Sets the magazine zone i d of this magazine content.
	 *
	 * @param MagazineZoneID the magazine zone i d of this magazine content
	 */
	public void setMagazineZoneID(int MagazineZoneID);

	/**
	 * Returns the magazine i d of this magazine content.
	 *
	 * @return the magazine i d of this magazine content
	 */
	public int getMagazineID();

	/**
	 * Sets the magazine i d of this magazine content.
	 *
	 * @param MagazineID the magazine i d of this magazine content
	 */
	public void setMagazineID(int MagazineID);

	/**
	 * Returns the author of this magazine content.
	 *
	 * @return the author of this magazine content
	 */
	@AutoEscape
	public String getAuthor();

	/**
	 * Sets the author of this magazine content.
	 *
	 * @param Author the author of this magazine content
	 */
	public void setAuthor(String Author);

	/**
	 * Returns the jobtitle of this magazine content.
	 *
	 * @return the jobtitle of this magazine content
	 */
	@AutoEscape
	public String getJobtitle();

	/**
	 * Sets the jobtitle of this magazine content.
	 *
	 * @param Jobtitle the jobtitle of this magazine content
	 */
	public void setJobtitle(String Jobtitle);

	/**
	 * Returns the viewed count of this magazine content.
	 *
	 * @return the viewed count of this magazine content
	 */
	public int getViewedCount();

	/**
	 * Sets the viewed count of this magazine content.
	 *
	 * @param ViewedCount the viewed count of this magazine content
	 */
	public void setViewedCount(int ViewedCount);

	/**
	 * Returns the sort order of this magazine content.
	 *
	 * @return the sort order of this magazine content
	 */
	public int getSortOrder();

	/**
	 * Sets the sort order of this magazine content.
	 *
	 * @param SortOrder the sort order of this magazine content
	 */
	public void setSortOrder(int SortOrder);

	/**
	 * Returns the mailed count of this magazine content.
	 *
	 * @return the mailed count of this magazine content
	 */
	public int getMailedCount();

	/**
	 * Sets the mailed count of this magazine content.
	 *
	 * @param MailedCount the mailed count of this magazine content
	 */
	public void setMailedCount(int MailedCount);

	/**
	 * Returns the creation date of this magazine content.
	 *
	 * @return the creation date of this magazine content
	 */
	public Date getCreationDate();

	/**
	 * Sets the creation date of this magazine content.
	 *
	 * @param CreationDate the creation date of this magazine content
	 */
	public void setCreationDate(Date CreationDate);

	/**
	 * Returns the modified date of this magazine content.
	 *
	 * @return the modified date of this magazine content
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this magazine content.
	 *
	 * @param ModifiedDate the modified date of this magazine content
	 */
	public void setModifiedDate(Date ModifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.viettel.portal.magazine.model.MagazineContent magazineContent);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.viettel.portal.magazine.model.MagazineContent> toCacheModel();

	@Override
	public com.viettel.portal.magazine.model.MagazineContent toEscapedModel();

	@Override
	public com.viettel.portal.magazine.model.MagazineContent toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}