/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.vcms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Comment service. Represents a row in the &quot;vcms_Comment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viettel.portal.vcms.model.impl.CommentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viettel.portal.vcms.model.impl.CommentImpl}.
 * </p>
 *
 * @author chuchv
 * @see Comment
 * @see com.viettel.portal.vcms.model.impl.CommentImpl
 * @see com.viettel.portal.vcms.model.impl.CommentModelImpl
 * @generated
 */
public interface CommentModel extends BaseModel<Comment>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a comment model instance should use the {@link Comment} interface instead.
	 */

	/**
	 * Returns the primary key of this comment.
	 *
	 * @return the primary key of this comment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this comment.
	 *
	 * @param primaryKey the primary key of this comment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the comment ID of this comment.
	 *
	 * @return the comment ID of this comment
	 */
	public long getCommentId();

	/**
	 * Sets the comment ID of this comment.
	 *
	 * @param commentId the comment ID of this comment
	 */
	public void setCommentId(long commentId);

	/**
	 * Returns the group ID of this comment.
	 *
	 * @return the group ID of this comment
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this comment.
	 *
	 * @param groupId the group ID of this comment
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this comment.
	 *
	 * @return the company ID of this comment
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this comment.
	 *
	 * @param companyId the company ID of this comment
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this comment.
	 *
	 * @return the user ID of this comment
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this comment.
	 *
	 * @param userId the user ID of this comment
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this comment.
	 *
	 * @return the user uuid of this comment
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this comment.
	 *
	 * @param userUuid the user uuid of this comment
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this comment.
	 *
	 * @return the user name of this comment
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this comment.
	 *
	 * @param userName the user name of this comment
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this comment.
	 *
	 * @return the create date of this comment
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this comment.
	 *
	 * @param createDate the create date of this comment
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this comment.
	 *
	 * @return the modified date of this comment
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this comment.
	 *
	 * @param modifiedDate the modified date of this comment
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the distribution ID of this comment.
	 *
	 * @return the distribution ID of this comment
	 */
	public long getDistributionId();

	/**
	 * Sets the distribution ID of this comment.
	 *
	 * @param distributionId the distribution ID of this comment
	 */
	public void setDistributionId(long distributionId);

	/**
	 * Returns the distributed date of this comment.
	 *
	 * @return the distributed date of this comment
	 */
	public Date getDistributedDate();

	/**
	 * Sets the distributed date of this comment.
	 *
	 * @param distributedDate the distributed date of this comment
	 */
	public void setDistributedDate(Date distributedDate);

	/**
	 * Returns the full name of this comment.
	 *
	 * @return the full name of this comment
	 */
	@AutoEscape
	public String getFullName();

	/**
	 * Sets the full name of this comment.
	 *
	 * @param fullName the full name of this comment
	 */
	public void setFullName(String fullName);

	/**
	 * Returns the address of this comment.
	 *
	 * @return the address of this comment
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this comment.
	 *
	 * @param address the address of this comment
	 */
	public void setAddress(String address);

	/**
	 * Returns the email of this comment.
	 *
	 * @return the email of this comment
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this comment.
	 *
	 * @param email the email of this comment
	 */
	public void setEmail(String email);

	/**
	 * Returns the body of this comment.
	 *
	 * @return the body of this comment
	 */
	@AutoEscape
	public String getBody();

	/**
	 * Sets the body of this comment.
	 *
	 * @param body the body of this comment
	 */
	public void setBody(String body);

	/**
	 * Returns the visible of this comment.
	 *
	 * @return the visible of this comment
	 */
	public boolean getVisible();

	/**
	 * Returns <code>true</code> if this comment is visible.
	 *
	 * @return <code>true</code> if this comment is visible; <code>false</code> otherwise
	 */
	public boolean isVisible();

	/**
	 * Sets whether this comment is visible.
	 *
	 * @param visible the visible of this comment
	 */
	public void setVisible(boolean visible);

	/**
	 * Returns the ip address of this comment.
	 *
	 * @return the ip address of this comment
	 */
	@AutoEscape
	public String getIpAddress();

	/**
	 * Sets the ip address of this comment.
	 *
	 * @param ipAddress the ip address of this comment
	 */
	public void setIpAddress(String ipAddress);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.viettel.portal.vcms.model.Comment comment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.viettel.portal.vcms.model.Comment> toCacheModel();

	@Override
	public com.viettel.portal.vcms.model.Comment toEscapedModel();

	@Override
	public com.viettel.portal.vcms.model.Comment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}