/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.vcms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Legal_Content service. Represents a row in the &quot;Content&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viettel.portal.vcms.model.impl.Legal_ContentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viettel.portal.vcms.model.impl.Legal_ContentImpl}.
 * </p>
 *
 * @author chuchv
 * @see Legal_Content
 * @see com.viettel.portal.vcms.model.impl.Legal_ContentImpl
 * @see com.viettel.portal.vcms.model.impl.Legal_ContentModelImpl
 * @generated
 */
public interface Legal_ContentModel extends BaseModel<Legal_Content> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a legal_ content model instance should use the {@link Legal_Content} interface instead.
	 */

	/**
	 * Returns the primary key of this legal_ content.
	 *
	 * @return the primary key of this legal_ content
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this legal_ content.
	 *
	 * @param primaryKey the primary key of this legal_ content
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the i d of this legal_ content.
	 *
	 * @return the i d of this legal_ content
	 */
	public int getID();

	/**
	 * Sets the i d of this legal_ content.
	 *
	 * @param ID the i d of this legal_ content
	 */
	public void setID(int ID);

	/**
	 * Returns the content i d of this legal_ content.
	 *
	 * @return the content i d of this legal_ content
	 */
	public int getContentID();

	/**
	 * Sets the content i d of this legal_ content.
	 *
	 * @param ContentID the content i d of this legal_ content
	 */
	public void setContentID(int ContentID);

	/**
	 * Returns the version of this legal_ content.
	 *
	 * @return the version of this legal_ content
	 */
	public int getVersion();

	/**
	 * Sets the version of this legal_ content.
	 *
	 * @param Version the version of this legal_ content
	 */
	public void setVersion(int Version);

	/**
	 * Returns the creation date of this legal_ content.
	 *
	 * @return the creation date of this legal_ content
	 */
	public Date getCreationDate();

	/**
	 * Sets the creation date of this legal_ content.
	 *
	 * @param CreationDate the creation date of this legal_ content
	 */
	public void setCreationDate(Date CreationDate);

	/**
	 * Returns the modified date of this legal_ content.
	 *
	 * @return the modified date of this legal_ content
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this legal_ content.
	 *
	 * @param ModifiedDate the modified date of this legal_ content
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the byline of this legal_ content.
	 *
	 * @return the byline of this legal_ content
	 */
	@AutoEscape
	public String getByline();

	/**
	 * Sets the byline of this legal_ content.
	 *
	 * @param Byline the byline of this legal_ content
	 */
	public void setByline(String Byline);

	/**
	 * Returns the headline of this legal_ content.
	 *
	 * @return the headline of this legal_ content
	 */
	@AutoEscape
	public String getHeadline();

	/**
	 * Sets the headline of this legal_ content.
	 *
	 * @param Headline the headline of this legal_ content
	 */
	public void setHeadline(String Headline);

	/**
	 * Returns the tagline of this legal_ content.
	 *
	 * @return the tagline of this legal_ content
	 */
	@AutoEscape
	public String getTagline();

	/**
	 * Sets the tagline of this legal_ content.
	 *
	 * @param Tagline the tagline of this legal_ content
	 */
	public void setTagline(String Tagline);

	/**
	 * Returns the teaser of this legal_ content.
	 *
	 * @return the teaser of this legal_ content
	 */
	@AutoEscape
	public String getTeaser();

	/**
	 * Sets the teaser of this legal_ content.
	 *
	 * @param Teaser the teaser of this legal_ content
	 */
	public void setTeaser(String Teaser);

	/**
	 * Returns the body of this legal_ content.
	 *
	 * @return the body of this legal_ content
	 */
	@AutoEscape
	public String getBody();

	/**
	 * Sets the body of this legal_ content.
	 *
	 * @param Body the body of this legal_ content
	 */
	public void setBody(String Body);

	/**
	 * Returns the avatar of this legal_ content.
	 *
	 * @return the avatar of this legal_ content
	 */
	@AutoEscape
	public String getAvatar();

	/**
	 * Sets the avatar of this legal_ content.
	 *
	 * @param Avatar the avatar of this legal_ content
	 */
	public void setAvatar(String Avatar);

	/**
	 * Returns the image url of this legal_ content.
	 *
	 * @return the image url of this legal_ content
	 */
	@AutoEscape
	public String getImageUrl();

	/**
	 * Sets the image url of this legal_ content.
	 *
	 * @param ImageUrl the image url of this legal_ content
	 */
	public void setImageUrl(String ImageUrl);

	/**
	 * Returns the image description of this legal_ content.
	 *
	 * @return the image description of this legal_ content
	 */
	@AutoEscape
	public String getImageDescription();

	/**
	 * Sets the image description of this legal_ content.
	 *
	 * @param ImageDescription the image description of this legal_ content
	 */
	public void setImageDescription(String ImageDescription);

	/**
	 * Returns the image align of this legal_ content.
	 *
	 * @return the image align of this legal_ content
	 */
	public int getImageAlign();

	/**
	 * Sets the image align of this legal_ content.
	 *
	 * @param ImageAlign the image align of this legal_ content
	 */
	public void setImageAlign(int ImageAlign);

	/**
	 * Returns the zone i d of this legal_ content.
	 *
	 * @return the zone i d of this legal_ content
	 */
	public int getZoneID();

	/**
	 * Sets the zone i d of this legal_ content.
	 *
	 * @param ZoneID the zone i d of this legal_ content
	 */
	public void setZoneID(int ZoneID);

	/**
	 * Returns the source of this legal_ content.
	 *
	 * @return the source of this legal_ content
	 */
	@AutoEscape
	public String getSource();

	/**
	 * Sets the source of this legal_ content.
	 *
	 * @param Source the source of this legal_ content
	 */
	public void setSource(String Source);

	/**
	 * Returns the status of this legal_ content.
	 *
	 * @return the status of this legal_ content
	 */
	public int getStatus();

	/**
	 * Sets the status of this legal_ content.
	 *
	 * @param Status the status of this legal_ content
	 */
	public void setStatus(int Status);

	/**
	 * Returns the author of this legal_ content.
	 *
	 * @return the author of this legal_ content
	 */
	@AutoEscape
	public String getAuthor();

	/**
	 * Sets the author of this legal_ content.
	 *
	 * @param Author the author of this legal_ content
	 */
	public void setAuthor(String Author);

	/**
	 * Returns the editor of this legal_ content.
	 *
	 * @return the editor of this legal_ content
	 */
	@AutoEscape
	public String getEditor();

	/**
	 * Sets the editor of this legal_ content.
	 *
	 * @param Editor the editor of this legal_ content
	 */
	public void setEditor(String Editor);

	/**
	 * Returns the approver of this legal_ content.
	 *
	 * @return the approver of this legal_ content
	 */
	@AutoEscape
	public String getApprover();

	/**
	 * Sets the approver of this legal_ content.
	 *
	 * @param Approver the approver of this legal_ content
	 */
	public void setApprover(String Approver);

	/**
	 * Returns the deployer of this legal_ content.
	 *
	 * @return the deployer of this legal_ content
	 */
	@AutoEscape
	public String getDeployer();

	/**
	 * Sets the deployer of this legal_ content.
	 *
	 * @param Deployer the deployer of this legal_ content
	 */
	public void setDeployer(String Deployer);

	/**
	 * Returns the authors of this legal_ content.
	 *
	 * @return the authors of this legal_ content
	 */
	@AutoEscape
	public String getAuthors();

	/**
	 * Sets the authors of this legal_ content.
	 *
	 * @param Authors the authors of this legal_ content
	 */
	public void setAuthors(String Authors);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.viettel.portal.vcms.model.Legal_Content legal_Content);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.viettel.portal.vcms.model.Legal_Content> toCacheModel();

	@Override
	public com.viettel.portal.vcms.model.Legal_Content toEscapedModel();

	@Override
	public com.viettel.portal.vcms.model.Legal_Content toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}