/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package com.viettel.portal.vcms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Legal_ContentProfit service. Represents a row in the &quot;ContentProfit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viettel.portal.vcms.model.impl.Legal_ContentProfitModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viettel.portal.vcms.model.impl.Legal_ContentProfitImpl}.
 * </p>
 *
 * @author chuchv
 * @see Legal_ContentProfit
 * @see com.viettel.portal.vcms.model.impl.Legal_ContentProfitImpl
 * @see com.viettel.portal.vcms.model.impl.Legal_ContentProfitModelImpl
 * @generated
 */
public interface Legal_ContentProfitModel extends BaseModel<Legal_ContentProfit> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a legal_ content profit model instance should use the {@link Legal_ContentProfit} interface instead.
	 */

	/**
	 * Returns the primary key of this legal_ content profit.
	 *
	 * @return the primary key of this legal_ content profit
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this legal_ content profit.
	 *
	 * @param primaryKey the primary key of this legal_ content profit
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the content i d of this legal_ content profit.
	 *
	 * @return the content i d of this legal_ content profit
	 */
	public int getContentID();

	/**
	 * Sets the content i d of this legal_ content profit.
	 *
	 * @param ContentID the content i d of this legal_ content profit
	 */
	public void setContentID(int ContentID);

	/**
	 * Returns the content type i d of this legal_ content profit.
	 *
	 * @return the content type i d of this legal_ content profit
	 */
	public int getContentTypeID();

	/**
	 * Sets the content type i d of this legal_ content profit.
	 *
	 * @param ContentTypeID the content type i d of this legal_ content profit
	 */
	public void setContentTypeID(int ContentTypeID);

	/**
	 * Returns the headline of this legal_ content profit.
	 *
	 * @return the headline of this legal_ content profit
	 */
	@AutoEscape
	public String getHeadline();

	/**
	 * Sets the headline of this legal_ content profit.
	 *
	 * @param Headline the headline of this legal_ content profit
	 */
	public void setHeadline(String Headline);

	/**
	 * Returns the cost of this legal_ content profit.
	 *
	 * @return the cost of this legal_ content profit
	 */
	public double getCost();

	/**
	 * Sets the cost of this legal_ content profit.
	 *
	 * @param Cost the cost of this legal_ content profit
	 */
	public void setCost(double Cost);

	/**
	 * Returns the author of this legal_ content profit.
	 *
	 * @return the author of this legal_ content profit
	 */
	@AutoEscape
	public String getAuthor();

	/**
	 * Sets the author of this legal_ content profit.
	 *
	 * @param Author the author of this legal_ content profit
	 */
	public void setAuthor(String Author);

	/**
	 * Returns the status of this legal_ content profit.
	 *
	 * @return the status of this legal_ content profit
	 */
	public int getStatus();

	/**
	 * Sets the status of this legal_ content profit.
	 *
	 * @param Status the status of this legal_ content profit
	 */
	public void setStatus(int Status);

	/**
	 * Returns the creation date of this legal_ content profit.
	 *
	 * @return the creation date of this legal_ content profit
	 */
	public Date getCreationDate();

	/**
	 * Sets the creation date of this legal_ content profit.
	 *
	 * @param CreationDate the creation date of this legal_ content profit
	 */
	public void setCreationDate(Date CreationDate);

	/**
	 * Returns the modified date of this legal_ content profit.
	 *
	 * @return the modified date of this legal_ content profit
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this legal_ content profit.
	 *
	 * @param ModifiedDate the modified date of this legal_ content profit
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the distributed date of this legal_ content profit.
	 *
	 * @return the distributed date of this legal_ content profit
	 */
	public Date getDistributedDate();

	/**
	 * Sets the distributed date of this legal_ content profit.
	 *
	 * @param DistributedDate the distributed date of this legal_ content profit
	 */
	public void setDistributedDate(Date DistributedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.viettel.portal.vcms.model.Legal_ContentProfit legal_ContentProfit);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.viettel.portal.vcms.model.Legal_ContentProfit> toCacheModel();

	@Override
	public com.viettel.portal.vcms.model.Legal_ContentProfit toEscapedModel();

	@Override
	public com.viettel.portal.vcms.model.Legal_ContentProfit toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}